# Data Preparation

In [51]:
import pandas
import matplotlib.pyplot as plt
from collections import Counter
import string
import numpy as np

from tensorflow.keras import layers
from tensorflow.keras import losses

wf = pandas.read_csv("./EMPOLITICON.csv")
wf

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,16/07/2021,Vladimir Putin,Meeting of APEC Economic Leaders,"Madam Chair,\n\nColleagues,\n\nFirst of all, ...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,OPTIMISM,DEVELOPMENT
1,Russia,2021-09-05 00:00:00,Vladimir Putin,Victory Parade on Red Square,"Citizens of Russia,\n\nDear veterans,\n\nComra...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,JOY,NATIONALISM
2,Russia,2021-08-04 00:00:00,Vladimir Putin,Meeting on the results of implementing Preside...,"Good afternoon, colleagues.\n\nLet’s start.\n\...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,DEVELOPMENT
3,Russia,21-11-2020,Vladimir Putin,G20 Summit,"Colleagues,\n\nThe scope of problems humanity ...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,DEVELOPMENT
4,Russia,20-11-2020,Vladimir Putin,Address to participants in Nuremberg Lessons f...,"Colleagues, friends,\n\nFirst of all, I would ...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,UPSET,EXTREMISM
...,...,...,...,...,...,...,...,...,...,...
2005,USA,05/02/2013,Barack Obama,\nRemarks by the President,"Good afternoon, everybody. \n\nI wanted to sa...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,NEUTRAL,DEVELOPMENT
2006,USA,04/02/2013,Barack Obama,\nRemarks by the President on Preventing Gun V...,"Hello, everybody. Please have a seat. Have a...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,NEUTRAL,OTHERS
2007,USA,02/02/2013,Barack Obama,\nWeekly Address: A Balanced Approach to Growi...,"Hi, everybody. \n\nIn the coming weeks, we fa...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,OPTIMISM,DEVELOPMENT
2008,USA,28/01/2013,Barack Obama,\nRemarks by the President Before Meeting with...,"Well, Vice President Biden and I just want to...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,OPTIMISM,OTHERS
2009,USA,21/01/2013,Barack Obama,\nInaugural Address by President Barack Obama,"Vice President Biden, Mr. Chief Justice,\nmemb...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,JOY,OTHERS

In [52]:
# shuffing the data
wf = wf.sample(frac=1).reset_index(drop=True)
wf

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,2002-08-07 00:00:00,Vladimir Putin,Extracts from Opening Remarks at a Security Co...,Good afternoon.\n\nToday we are discussing the...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,DEVELOPMENT
1,USA,2021-09-02 00:00:00,Joe Biden,Remarks by President Biden in Virtual Call for...,"THE PRESIDENT: Well, thank you very much. I ...",President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,NEUTRAL,OTHERS
2,Russia,24-12-2007,Vladimir Putin,Speech at the Opening Ceremony for the Year of...,Dear friends!\n\nWe are in the days leading up...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,OTHERS
3,USA,15/12/2015,Barack Obama,\nRemarks by the President at Naturalization C...,"Well, good morning, everybody. Thank you Depu...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,JOY,NATIONALISM
4,Russia,2005-09-11 00:00:00,Vladimir Putin,Closing Remarks at Meeting with the Armed Forc...,I would like to say a few words on what I hea...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,OTHERS
...,...,...,...,...,...,...,...,...,...,...
2005,China,2016-06-20 00:00:00,H.E. Wang Yi,Build a New Type of International Relations Fe...,"In March 2013 during his visit to Russia, Gene...",State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,OPTIMISM,INTERNATIONAL AFFAIRS
2006,China,2020-09-08 00:00:00,H.E. Wang Yi,"Upholding Multilateralism, Fairness and Justic...","Distinguished Guests,\nColleagues,\nLadies and...",State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,NEUTRAL,DEVELOPMENT
2007,United Kingdom,19 July 2011,David Cameron,"PM's speech on aid, trade and democracy",Today the eyes of the world are on another par...,Prime Minister,David Cameron,https://www.gov.uk/government/speeches/pms-spe...,OPTIMISM,DEVELOPMENT
2008,Russia,26-10-2017,Vladimir Putin,Security Council meeting,"Good afternoon, colleagues.\n\nToday we will d...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,DEVELOPMENT
2009,China,2020-09-03 00:00:00,H.E. Wang Yi,Strengthening Cooperation to Weather the Tryin...,Your Highness Prince Faisal bin Farhan Al Saud...,State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,NEUTRAL,DEVELOPMENT

In [53]:
def count_unique_word(wf):
    count = Counter()
    for word in wf['Emotion']:
        count[word] += 1
    return count

counter = count_unique_word(wf)

In [54]:
print(counter.most_common())

[('NEUTRAL', 589), ('OPTIMISM', 583), ('JOY', 525), ('UPSET', 313)]

Setting labels for a multi-classification problem

In [55]:
#labeling the emotion column such that they are classified as neutral, positive, or negative
for i in range(len(wf)):
    if wf['Emotion'][i] == counter.most_common()[0][0]:
        wf['Emotion'][i] = 0
    elif wf['Emotion'][i] == counter.most_common()[1][0]:
        wf['Emotion'][i] = 1
    elif wf['Emotion'][i] == counter.most_common()[2][0]:
        wf['Emotion'][i] = 1
    elif wf['Emotion'][i] == counter.most_common()[3][0]:
        wf['Emotion'][i] = 2

#these labels will be used to train the model

/tmp/ipykernel_1192/1175571102.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Emotion'][i] = 0
/tmp/ipykernel_1192/1175571102.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Emotion'][i] = 1
/tmp/ipykernel_1192/1175571102.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Emotion'][i] = 1
/tmp/ipykernel_1192/1175571102.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Emotion'][i] = 2

In [56]:
wf

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,2002-08-07 00:00:00,Vladimir Putin,Extracts from Opening Remarks at a Security Co...,Good afternoon.\n\nToday we are discussing the...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,DEVELOPMENT
1,USA,2021-09-02 00:00:00,Joe Biden,Remarks by President Biden in Virtual Call for...,"THE PRESIDENT: Well, thank you very much. I ...",President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,0,OTHERS
2,Russia,24-12-2007,Vladimir Putin,Speech at the Opening Ceremony for the Year of...,Dear friends!\n\nWe are in the days leading up...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,OTHERS
3,USA,15/12/2015,Barack Obama,\nRemarks by the President at Naturalization C...,"Well, good morning, everybody. Thank you Depu...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,NATIONALISM
4,Russia,2005-09-11 00:00:00,Vladimir Putin,Closing Remarks at Meeting with the Armed Forc...,I would like to say a few words on what I hea...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,OTHERS
...,...,...,...,...,...,...,...,...,...,...
2005,China,2016-06-20 00:00:00,H.E. Wang Yi,Build a New Type of International Relations Fe...,"In March 2013 during his visit to Russia, Gene...",State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,1,INTERNATIONAL AFFAIRS
2006,China,2020-09-08 00:00:00,H.E. Wang Yi,"Upholding Multilateralism, Fairness and Justic...","Distinguished Guests,\nColleagues,\nLadies and...",State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,0,DEVELOPMENT
2007,United Kingdom,19 July 2011,David Cameron,"PM's speech on aid, trade and democracy",Today the eyes of the world are on another par...,Prime Minister,David Cameron,https://www.gov.uk/government/speeches/pms-spe...,1,DEVELOPMENT
2008,Russia,26-10-2017,Vladimir Putin,Security Council meeting,"Good afternoon, colleagues.\n\nToday we will d...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,DEVELOPMENT
2009,China,2020-09-03 00:00:00,H.E. Wang Yi,Strengthening Cooperation to Weather the Tryin...,Your Highness Prince Faisal bin Farhan Al Saud...,State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,0,DEVELOPMENT

In [57]:
# wf = wf.head(739)

In [58]:
wf.iloc[76]['Text_of_Speech']

'Your Excellencies Heads of State and Government,\nYour Excellencies Heads of International Organizations,\nYour Excellencies Members of the Board of Directors of the Boao Forum for Asia,\nDistinguished Guests,\nLadies and Gentlemen,\nDear Friends,\n\n"True friendship brings people close however far apart they may be." It gives me great pleasure to attend the Boao Forum for Asia Annual Conference 2021 and meet you all in this cloud meeting. Let me begin by extending, on behalf of the Chinese government and people and also in my own name, a warm welcome to all the guests participating both in person and online, and cordial greetings and best wishes to all friends old and new.\n\nThis year marks the 20th anniversary of the Boao Forum. Over these two decades, Asian countries have advanced regional economic integration and worked in unison to pursue both economic and social development, which has turned Asia into the most vibrant and promising region in the global economy. Asia has also stood with the rest of the world in the face of terrorism, the Indian Ocean tsunami, the international financial crisis, COVID-19 and other traditional and non-traditional security threats, which has helped maintain stability and security in the region. As an important member of the Asian family, China has kept deepening reform and opening-up while promoting regional cooperation, thus achieving progress and development in tandem with the rest of Asia and the world. It is fair to say that this Forum has borne witness to the extraordinary journey of China, of Asia and of the world, and has exerted a significant influence in boosting development in Asia and beyond.\n\nLadies and Gentlemen,\n\nFriends,\n\nThis year\'s annual conference is convened against a very special background. The theme of the conference-"A World in Change: Join Hands to Strengthen Global Governance and Advance Belt and Road Cooperation"-is most opportune and relevant under the current circumstances.\n\nNow, the combined forces of changes and a pandemic both unseen in a century have brought the world into a phase of fluidity and transformation. Instability and uncertainty are clearly on the rise. Humanity is facing growing governance deficit, trust deficit, development deficit, and peace deficit. Much remains to be done to achieve universal security and common development. That said, there is no fundamental change in the trend toward a multi-polar world; economic globalization is showing renewed resilience; and the call for upholding multilateralism and enhancing communication and coordination has grown stronger. While we live in an age rife with challenges, it is also an age full of hope.\n\nWhere should humanity go from here? What kind of future should we create for future generations? As we try to answer these important questions, it is crucial that we bear in mind the shared interests of mankind and make responsible and wise choices.\n\nChina calls on all countries in Asia and beyond to answer the call of our times, defeat the pandemic through solidarity, strengthen global governance, and keep pursuing a community with a shared future for mankind.\n\n- We need consultation on an equal footing to create a future of shared benefits. Global governance should reflect the evolving political and economic landscape in the world, conform to the historical trend of peace, development and win-win cooperation, and meet the practical needs in addressing global challenges. We need to follow the principles of extensive consultation, joint contribution and shared benefits, uphold true multilateralism, and make the global governance system more fair and equitable. We need to safeguard the UN-centered international system, preserve the international order underpinned by international law, and uphold the multilateral trading system with the World Trade Organization at its core. World affairs should be handled through extensive consultation, and the future of the world should be decided by all countries working together. We must not let the rules set by one or a few countries be imposed on others, or allow unilateralism pursued by certain countries to set the pace for the whole world. What we need in today\'s world is justice, not hegemony. Big countries should behave in a manner befitting their status and with a greater sense of responsibility.\n\n- We need openness and innovation to create a future of development and prosperity. Openness is essential for development and progress. It also holds the key to post-COVID economic recovery. We need to promote trade and investment liberalization and facilitation, deepen regional economic integration, and enhance supply, industrial, data and human resources chains, with a view to building an open world economy. We need to deepen partnerships for connectivity and strengthen infrastructural links to keep the arteries of economic activities unclogged. We must seize the historical opportunities in a new round of scientific and technological revolution and industrial transformation, boost the digital economy, and step up exchanges and cooperation in such areas as artificial intelligence, biomedicine and modern energy, so that the fruits of scientific and technological innovation can be turned into greater benefits for people in all countries. In this age of economic globalization, openness and integration is an unstoppable historical trend. Attempts to "erect walls" or "decouple" run counter to the law of economics and market principles. They would hurt others\' interests without benefiting oneself.\n\n- We need solidarity and cooperation to create a future of health and security. In the ongoing fight against COVID-19, victory will be ours at the end of the day. We must put people and their lives above anything else, scale up information sharing and collective efforts, enhance public health and medical cooperation, and give full play to the key role of the World Health Organization (WHO). It is important that we bolster international cooperation on the R&D, production and distribution of vaccines and increase their accessibility and affordability in developing countries so that everyone in the world can access and afford the vaccines they need. It is also important that we take comprehensive measures to improve global governance on public health security and work together for a global community of health for all. We need to follow the philosophy of green development, advance international cooperation on climate change, and do more to implement the Paris Agreement on climate change. The principle of common but differentiated responsibilities must be upheld, and concerns of developing countries on capital, technology and capacity building must be addressed.\n\n- We need commitment to justice to create a future of mutual respect and mutual learning. Diversity is what defines our world and makes human civilization fascinating. The COVID-19 pandemic has made it all the more clear to people around the world that we must reject the cold-war and zero-sum mentality and oppose a new "Cold War" and ideological confrontation in whatever forms. In state-to-state relations, the principles of equality, mutual respect and mutual trust must be put front and center. Bossing others around or meddling in others\' internal affairs would not get one any support. We must advocate peace, development, equity, justice, democracy and freedom, which are common values of humanity, and encourage exchanges and mutual learning among civilizations to promote the progress of human civilization.\n\nIn this context, I would like to announce that once the pandemic gets under control, China will host the second Conference on Dialogue of Asian Civilizations as part of our active efforts to promote inter-civilization dialogue in Asia and beyond.\n\nLadies and Gentlemen,\n\nFriends,\n\nI have noted on various occasions that the Belt and Road Initiative (BRI) is a public road open to all, not a private path owned by one single party. All interested countries are welcome aboard to take part in the cooperation and share in its benefits. Belt and Road cooperation pursues development, aims at mutual benefits, and conveys a message of hope.\n\nGoing forward, we will continue to work with other parties in high-quality Belt and Road cooperation. We will follow the principles of extensive consultation, joint contribution and shared benefits, and champion the philosophy of open, green and clean cooperation, in a bid to make Belt and Road cooperation high-standard, people-centered and sustainable.\n\n- We will build a closer partnership for health cooperation. Chinese businesses have already started joint vaccine production in BRI participating countries such as Indonesia, Brazil, the United Arab Emirates, Malaysia, Pakistan and Turkey. We will expand cooperation with various parties in infectious disease control, public health, traditional medicine and other areas to jointly protect the lives and health of people in all countries.\n\n- We will build a closer partnership for connectivity. China will work with all sides to promote "hard connectivity" of infrastructure and "soft connectivity" of rules and standards, ensure unimpeded channels for trade and investment cooperation, and actively develop Silk Road e-commerce, all in a bid to open up a bright prospect for integrated development.\n\n- We will build a closer partnership for green development. We could strengthen cooperation on green infrastructure, green energy and green finance, and improve the BRI International Green Development Coalition, the Green Investment Principles for the Belt and Road Development, and other multilateral cooperation platforms to make green a defining feature of Belt and Road cooperation.\n\n- We will build a closer partnership for openness and inclusiveness. A World Bank report suggests that by 2030, Belt and Road projects could help lift 7.6 million people from extreme poverty and 32 million people from moderate poverty across the world. We will act in the spirit of openness and inclusiveness as we work with all willing participants to build the BRI into a pathway to poverty alleviation and growth, which will contribute positively to the common prosperity of humankind.\n\nLadies and Gentlemen,\n\nFriends,\n\nThe year 2021 marks the centenary of the Communist Party of China (CPC). Over the last century, the CPC has striven forward against all odds in a relentless pursuit of happiness for the Chinese people, rejuvenation for the Chinese nation, and the common good for the world. As a result, the Chinese nation has achieved a great transformation from standing up to growing rich, and to becoming stronger, and has thus made a notable contribution to human civilization and progress. China will continue to play its part in building world peace, promoting global development, and defending international order.\n\nChina will stay committed to peace, development, cooperation and mutual benefit, develop friendship and cooperation with other countries on the basis of the Five Principles of Peaceful Coexistence, and promote a new type of international relations. China will continue to carry out anti-COVID cooperation with the WHO and other countries, honor its commitment of making vaccines a global public good, and do more to help developing countries defeat the virus. However strong it may grow, China will never seek hegemony, expansion, or a sphere of influence. Nor will China ever engage in an arms race. China will take an active part in multilateral cooperation on trade and investment, fully implement the Foreign Investment Law and its supporting rules and regulations, cut further the negative list on foreign investment, continue to develop the Hainan Free Trade Port, and develop new systems for a higher-standard open economy. All are welcome to share in the vast opportunities of the Chinese market.\n\nLadies and Gentlemen,\n\nFriends,\n\n"By setting sail together, we could ride the wind, break the waves, and brave the journey of ten thousand miles." We may at times encounter stormy waves and dangerous rapids, but as long as we pool our efforts and keep to the right direction, the giant vessel of human development will stay on an even keel and sail toward a brighter future.\n\nThank you.'

In [59]:
## one thing we can do is to use the model from the presidential classifier and then, if a given speech is classified
## as angry or some other negative mood, and it includes the word "US, NATO", or something related to the west, we classify it as adversarial

In [60]:
#removing the punctuation

## Yet to apply this to the data

def remove_punctuation(text):
    translator = str.maketrans("", "", string.punctuation)
    return text.translate(translator)

In [61]:
#removing the stop words (commonly used words that do not add much meaning to a sentence)

## Yet to actually apply this function to the data

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop = set(stopwords.words("english"))

def remove_stopwords(text):
    #removes stop words
    filtered_words = [word.lower() for word in text.split() if word.lower() not in stop]
    return " ".join(filtered_words)

[nltk_data] Downloading package stopwords to /home/yash/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [62]:
#cleaning up the speeches so that common stopwords and puntuation are removed
for i in range(len(wf['Text_of_Speech'])):
    wf['Text_of_Speech'][i] = remove_punctuation(wf['Text_of_Speech'][i])
    wf['Text_of_Speech'][i] = remove_stopwords(wf['Text_of_Speech'][i])

/tmp/ipykernel_1192/2134825500.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Text_of_Speech'][i] = remove_punctuation(wf['Text_of_Speech'][i])
/tmp/ipykernel_1192/2134825500.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Text_of_Speech'][i] = remove_stopwords(wf['Text_of_Speech'][i])

In [63]:
#drop rows without string in speech
for i in range(len(wf) - 1, -1, -1):
        if not (isinstance(wf.iloc[i]['Text_of_Speech'], str)):
                wf = wf.drop(i)

In [64]:
#counting the number of unique words in each speech


def count_unique_word(wf_training):
    count = Counter()
    for i in range(len(wf_training)):
        for word in wf_training.iloc[i]['Text_of_Speech'].split():
            count[word] += 1
    return count

counter = count_unique_word(wf)

In [65]:
counter

Counter({'people': 9977,
         '—': 8222,
         'new': 6587,
         'world': 6530,
         'work': 6325,
         'us': 6261,
         'china': 6246,
         'countries': 6156,
         'development': 6030,
         'one': 5367,
         'also': 5297,
         'country': 5190,
         'cooperation': 5139,
         'today': 4997,
         'need': 4856,
         'make': 4751,
         'thank': 4400,
         'years': 4319,
         'like': 4236,
         'must': 4210,
         'going': 4136,
         'want': 4067,
         'know': 4061,
         'would': 3998,
         'it’s': 3995,
         'time': 3944,
         'international': 3876,
         'economic': 3761,
         'many': 3709,
         'applause': 3698,
         'first': 3525,
         'we’re': 3520,
         '–': 3500,
         'year': 3467,
         'security': 3461,
         'united': 3394,
         'economy': 3278,
         'states': 3250,
         'that’s': 3248,
         'every': 3222,
         'great': 3150,
         'important': 3121,
         'get': 3113,
         'together': 3081,
         'american': 3075,
         'good': 2925,
         'government': 2885,
         'way': 2808,
         'much': 2796,
         'america': 2769,
         'support': 2767,
         'state': 2744,
         'right': 2705,
         'global': 2697,
         'take': 2653,
         'help': 2564,
         'well': 2558,
         'president': 2520,
         'think': 2490,
         'two': 2466,
         'future': 2365,
         'system': 2354,
         'national': 2342,
         'made': 2333,
         'even': 2319,
         'russia': 2247,
         'law': 2237,
         'last': 2180,
         'continue': 2167,
         'say': 2143,
         'we’ve': 2136,
         'working': 2110,
         'back': 2108,
         'growth': 2096,
         'chinese': 2063,
         'see': 2031,
         'peace': 2019,
         'americans': 2013,
         'trade': 1987,
         'said': 1972,
         'jobs': 1960,
         'better': 1931,
         'come': 1918,
         'part': 1885,
         'still': 1869,
         'day': 1800,
         'families': 1777,
         'including': 1768,
         'community': 1750,
         'got': 1749,
         'business': 1730,
         'nation': 1716,
         'efforts': 1705,
         'build': 1701,
         'sure': 1693,
         'already': 1687,
         'i’m': 1677,
         'russian': 1674,
         'around': 1650,
         'keep': 1650,
         'course': 1639,
         'progress': 1631,
         'let': 1629,
         'lives': 1628,
         'common': 1627,
         'done': 1609,
         'health': 1595,
         'could': 1594,
         'long': 1581,
         'life': 1581,
         'never': 1568,
         'relations': 1521,
         'across': 1519,
         'political': 1517,
         'put': 1516,
         'interests': 1513,
         'go': 1507,
         'place': 1503,
         'million': 1487,
         'war': 1486,
         'history': 1486,
         'military': 1485,
         'past': 1484,
         'may': 1482,
         'public': 1473,
         'always': 1466,
         'regional': 1466,
         'nations': 1463,
         'social': 1457,
         'making': 1447,
         'believe': 1432,
         'number': 1422,
         'change': 1413,
         'friends': 1409,
         'give': 1402,
         'don’t': 1390,
         'problems': 1373,
         'issues': 1373,
         'things': 1364,
         'region': 1364,
         'investment': 1363,
         'job': 1351,
         'open': 1346,
         'ago': 1339,
         'federal': 1334,
         'care': 1331,
         'hope': 1327,
         'lot': 1325,
         'situation': 1303,
         'forward': 1303,
         'set': 1301,
         'energy': 1299,
         'look': 1298,
         'able': 1284,
         'end': 1281,
         'leaders': 1278,
         'home': 1277,
         'use': 1274,
         'since': 1271,
         'next': 1270,
         'percent': 1266,
         'children': 1255,
         'education': 1255,
         'citizens': 1251,
         'plan': 1244,
         'chinas': 1237,
         'best': 1236,
         'rights': 1232,
         'means': 1227,
         'they’re': 1226,
         'everybody': 1204,
         'developing': 1204,
         'power': 1196,
         'building': 1195,
         'ensure': 1192,
         'women': 1179,
         'major': 1178,
         'create': 1176,
         'policy': 1169,
         'another': 1168,
         'ever': 1168,
         'clear': 1167,
         'foreign': 1165,
         'without': 1163,
         'possible': 1162,
         'congress': 1158,
         'strong': 1156,
         'meeting': 1153,
         'reform': 1144,
         'second': 1134,
         'society': 1133,
         'order': 1129,
         'members': 1129,
         'businesses': 1128,
         'something': 1125,
         'hard': 1123,
         'areas': 1115,
         'different': 1115,
         'act': 1112,
         'opportunity': 1110,
         'free': 1110,
         'financial': 1103,
         'issue': 1102,
         'young': 1100,
         'human': 1098,
         'africa': 1094,
         'three': 1083,
         'laughter': 1082,
         'times': 1081,
         'service': 1079,
         'forces': 1074,
         'companies': 1065,
         'market': 1059,
         'big': 1054,
         'local': 1049,
         'protect': 1046,
         'billion': 1045,
         'far': 1041,
         'workers': 1028,
         'family': 1027,
         'regions': 1025,
         'challenges': 1025,
         'others': 1015,
         'whole': 1013,
         'measures': 1008,
         'infrastructure': 1002,
         'nuclear': 995,
         'road': 993,
         'colleagues': 993,
         'level': 992,
         'respect': 988,
         'un': 988,
         'general': 986,
         'pay': 986,
         'provide': 985,
         'mutual': 983,
         'shared': 979,
         'i’ve': 976,
         'become': 967,
         'council': 958,
         'everyone': 955,
         'role': 955,
         'cannot': 947,
         'thing': 945,
         'really': 945,
         'fight': 937,
         'fact': 936,
         'special': 932,
         'you’re': 932,
         'stand': 920,
         'needs': 919,
         'bring': 918,
         'everything': 911,
         'resources': 907,
         'process': 906,
         'god': 904,
         'promote': 901,
         'increase': 898,
         'taking': 896,
         'greater': 895,
         'stability': 893,
         'crisis': 892,
         'taken': 887,
         'action': 885,
         'share': 884,
         'real': 884,
         'high': 880,
         'effective': 876,
         'necessary': 875,
         'communities': 875,
         'deal': 873,
         'seen': 872,
         'tax': 864,
         'peoples': 862,
         'climate': 855,
         'services': 847,
         'force': 847,
         'among': 840,
         'full': 839,
         'opportunities': 839,
         'days': 836,
         'live': 833,
         'partners': 832,
         'ready': 822,
         'improve': 817,
         'there’s': 812,
         'start': 811,
         'achieve': 809,
         'justice': 808,
         'prosperity': 804,
         'point': 803,
         'europe': 800,
         'sector': 797,
         'parties': 787,
         'asia': 785,
         'house': 780,
         'money': 780,
         'months': 778,
         'folks': 778,
         'meet': 776,
         'millions': 775,
         'potential': 774,
         'strengthen': 764,
         'summit': 760,
         'step': 758,
         'responsibility': 756,
         'projects': 755,
         'five': 754,
         'mr': 754,
         'partnership': 753,
         'attention': 750,
         'coming': 750,
         'freedom': 749,
         'face': 748,
         'technology': 748,
         'african': 740,
         'address': 738,
         'example': 737,
         'strategic': 736,
         'within': 732,
         'problem': 732,
         'dear': 731,
         'ahead': 730,
         'thanks': 728,
         'middle': 728,
         'innovation': 725,
         'getting': 724,
         'success': 722,
         'yet': 720,
         'principles': 718,
         'men': 715,
         'conditions': 712,
         'took': 705,
         'especially': 704,
         'remember': 703,
         'east': 702,
         'school': 701,
         'committed': 701,
         'approach': 700,
         'proud': 699,
         'entire': 699,
         'week': 698,
         'key': 697,
         'joint': 695,
         'love': 693,
         'area': 692,
         'understand': 691,
         'single': 689,
         'secretary': 684,
         'fully': 684,
         'democracy': 682,
         'third': 681,
         'find': 679,
         'afghanistan': 675,
         'true': 674,
         'modern': 674,
         'information': 671,
         'office': 670,
         'growing': 667,
         'terrorism': 665,
         'agreement': 664,
         'develop': 662,
         'commitment': 662,
         'less': 657,
         'matter': 653,
         'minister': 652,
         'schools': 651,
         'small': 649,
         'decades': 648,
         'we’ll': 647,
         'steps': 645,
         'tell': 643,
         'rules': 643,
         'values': 642,
         'civil': 641,
         'given': 641,
         'moment': 640,
         'enforcement': 638,
         'often': 636,
         'budget': 636,
         'task': 635,
         'initiative': 635,
         'european': 634,
         'chance': 633,
         'came': 630,
         'difficult': 629,
         'actions': 628,
         'kind': 628,
         'union': 628,
         'safe': 626,
         'administration': 626,
         'quality': 622,
         'control': 622,
         'friendship': 621,
         'century': 618,
         'results': 617,
         'honor': 616,
         'incredible': 616,
         'fair': 614,
         'can’t': 613,
         'benefits': 613,
         'decisions': 613,
         'peaceful': 613,
         'south': 612,
         'close': 611,
         'spirit': 608,
         'environment': 608,
         'lead': 606,
         'leadership': 605,
         'dialogue': 603,
         'enough': 601,
         'path': 601,
         'rate': 600,
         'effort': 600,
         'wish': 597,
         'used': 596,
         'whether': 596,
         'poverty': 594,
         'finally': 592,
         'mean': 592,
         'four': 591,
         'turn': 587,
         'stronger': 587,
         'move': 587,
         'worked': 586,
         'sustainable': 586,
         'based': 583,
         'focus': 583,
         'laws': 582,
         'access': 581,
         'police': 581,
         'changes': 580,
         'covid19': 580,
         'virus': 580,
         'veterans': 580,
         'agenda': 579,
         'ways': 578,
         'main': 577,
         'call': 577,
         'thousands': 576,
         'little': 576,
         'along': 575,
         'experience': 575,
         'threat': 575,
         'bless': 570,
         'welcome': 568,
         'words': 568,
         'makes': 567,
         'priority': 566,
         'goal': 564,
         'capacity': 559,
         'remain': 559,
         'nearly': 559,
         'half': 557,
         'created': 555,
         'violence': 554,
         'ask': 554,
         'benefit': 551,
         'play': 550,
         'lost': 549,
         'serious': 549,
         'sense': 545,
         'stop': 545,
         'higher': 545,
         'advance': 544,
         'helping': 543,
         'stay': 541,
         'prime': 540,
         'uk': 540,
         'exchanges': 540,
         'living': 539,
         'particular': 538,
         'talk': 536,
         'science': 536,
         'simply': 536,
         'current': 535,
         'trust': 534,
         'legal': 534,
         'threats': 532,
         'ones': 531,
         'basis': 530,
         'line': 527,
         'various': 525,
         'recent': 524,
         'authorities': 524,
         'weeks': 523,
         'uphold': 523,
         'serve': 521,
         'nothing': 520,
         'strength': 520,
         'allow': 518,
         'terrorist': 518,
         'governance': 518,
         'you’ve': 517,
         'longterm': 517,
         'students': 517,
         'early': 516,
         'fighting': 515,
         'join': 515,
         'comprehensive': 513,
         'reason': 512,
         'party': 512,
         'almost': 511,
         'groups': 511,
         'agencies': 510,
         'behind': 509,
         'responsible': 508,
         'helped': 507,
         'strategy': 506,
         'grow': 506,
         'winwin': 506,
         'gentlemen': 503,
         'away': 502,
         'old': 502,
         'plans': 502,
         'xi': 502,
         'discuss': 501,
         'assistance': 499,
         'generation': 498,
         'training': 496,
         'britain': 496,
         'let’s': 495,
         'bill': 495,
         'pursue': 494,
         'border': 493,
         'remains': 493,
         'ladies': 493,
         'actually': 493,
         'industrial': 493,
         'standards': 492,
         'ministry': 492,
         'safety': 491,
         'industry': 490,
         'creating': 490,
         'thats': 490,
         'institutions': 487,
         'relationship': 487,
         'called': 485,
         'month': 484,
         'top': 484,
         'large': 483,
         'basic': 482,
         'positive': 481,
         'forum': 480,
         'vision': 480,
         'built': 478,
         'russia’s': 477,
         'visit': 476,
         'city': 476,
         'hold': 475,
         'cases': 475,
         'culture': 474,
         'asean': 474,
         'central': 473,
         'america’s': 473,
         'speak': 473,
         'armed': 472,
         'country’s': 471,
         'prevent': 471,
         'cut': 471,
         'private': 470,
         'research': 469,
         'enhance': 467,
         'belt': 467,
         'victory': 467,
         'several': 466,
         'looking': 466,
         'following': 464,
         'eu': 464,
         'north': 463,
         'met': 462,
         'developed': 462,
         'production': 462,
         'resolve': 461,
         'challenge': 460,
         'space': 459,
         'case': 457,
         'significant': 457,
         'protection': 456,
         'active': 456,
         'largest': 455,
         'beyond': 454,
         'follow': 454,
         'held': 453,
         'ideas': 453,
         'class': 452,
         'goals': 451,
         'faith': 451,
         'response': 451,
         'signed': 450,
         'terrorists': 450,
         'pandemic': 449,
         'anniversary': 449,
         'housing': 447,
         'happen': 447,
         'ground': 447,
         'involved': 445,
         'expand': 445,
         'position': 445,
         'truly': 445,
         'passed': 444,
         'soon': 443,
         'save': 443,
         'markets': 443,
         'raise': 442,
         'feel': 442,
         'economies': 442,
         'asian': 442,
         'deliver': 442,
         'leading': 440,
         'least': 440,
         'sides': 439,
         'result': 438,
         'land': 435,
         'recovery': 434,
         'saying': 433,
         'weapons': 433,
         'leave': 433,
         'interest': 433,
         'seek': 430,
         'legislation': 430,
         'certain': 430,
         'medical': 429,
         'fundamental': 428,
         'foundation': 428,
         'decision': 427,
         'events': 427,
         'reduce': 426,
         'coordination': 426,
         'troops': 425,
         'equal': 424,
         'vital': 424,
         'question': 424,
         'member': 423,
         'begin': 422,
         'brought': 422,
         'left': 421,
         'however': 420,
         'group': 418,
         'present': 417,
         'mission': 416,
         'cities': 416,
         'tasks': 416,
         'choice': 416,
         'isil': 416,
         'historic': 416,
         'what’s': 415,
         'child': 415,
         'syria': 415,
         'affairs': 414,
         'jointly': 414,
         'comes': 412,
         'rest': 412,
         'idea': 411,
         'trying': 411,
         'might': 411,
         'six': 411,
         'domestic': 410,
         'courage': 410,
         'hear': 409,
         'systems': 408,
         'dollars': 408,
         'policies': 408,
         'officers': 407,
         'confidence': 406,
         'insurance': 405,
         'representatives': 405,
         'needed': 405,
         'relevant': 404,
         'carry': 404,
         'iraq': 404,
         'contribution': 404,
         'reach': 403,
         'secure': 403,
         'overall': 403,
         'extraordinary': 403,
         'afternoon': 402,
         '10': 402,
         'agree': 402,
         'critical': 402,
         'cost': 402,
         'period': 401,
         'personnel': 401,
         'show': 400,
         'talking': 400,
         'actively': 400,
         'man': 399,
         'they’ve': 399,
         'happened': 397,
         'please': 397,
         'importance': 396,
         'cultural': 395,
         'therefore': 395,
         'rather': 394,
         'democratic': 394,
         'terms': 394,
         'dignity': 393,
         'heard': 393,
         'technologies': 393,
         'heart': 391,
         'federation': 391,
         'goods': 389,
         'manufacturing': 389,
         'towards': 388,
         'diplomacy': 387,
         'iran': 386,
         'organizations': 385,
         'sometimes': 385,
         'vote': 384,
         'kids': 384,
         'drug': 384,
         'equipment': 384,
         'instead': 383,
         'risk': 381,
         'demand': 381,
         'yesterday': 381,
         'doesn’t': 379,
         'affordable': 379,
         'diplomatic': 379,
         'criminal': 379,
         'levels': 379,
         'green': 378,
         'alone': 377,
         'framework': 376,
         'huge': 376,
         'executive': 375,
         'longer': 375,
         'particularly': 375,
         'heads': 375,
         'fellow': 374,
         'supply': 374,
         'implement': 373,
         'recently': 373,
         'biggest': 373,
         '100': 373,
         'republicans': 373,
         'speaker': 373,
         'view': 372,
         'crime': 372,
         'ensuring': 371,
         '50': 371,
         'allies': 371,
         'increasing': 370,
         'side': 370,
         'stage': 370,
         'white': 369,
         'beautiful': 369,
         'stable': 369,
         '20': 368,
         'team': 367,
         'weve': 367,
         'invest': 365,
         'agreed': 365,
         'goes': 365,
         'saw': 364,
         'investments': 364,
         'british': 364,
         'absolutely': 363,
         'rule': 363,
         'promoting': 363,
         'story': 362,
         'understanding': 362,
         'paid': 362,
         'beginning': 362,
         'people’s': 362,
         'greatest': 362,
         'throughout': 361,
         'achieved': 361,
         'places': 360,
         'improving': 359,
         'hand': 359,
         'activities': 359,
         'didn’t': 358,
         'republic': 358,
         'jinping': 358,
         'encourage': 358,
         'spread': 357,
         'told': 356,
         'toward': 356,
         'additional': 356,
         'went': 355,
         'stress': 354,
         'works': 354,
         'capital': 353,
         'defence': 353,
         'conflict': 353,
         'governments': 353,
         'started': 352,
         'maintain': 351,
         'department': 351,
         'integration': 351,
         'try': 351,
         'implementation': 350,
         'fourth': 349,
         'exchange': 349,
         'effectively': 349,
         'costs': 349,
         'internet': 349,
         'directly': 348,
         'draw': 348,
         'though': 348,
         'sea': 348,
         'morning': 347,
         'impact': 346,
         'thought': 346,
         'independent': 346,
         'asiapacific': 346,
         'opening': 345,
         'successful': 345,
         'majority': 344,
         'facing': 344,

In [66]:
num_unique_words = len(counter)

In [67]:
print(len(wf))

2010

In [68]:
#80% training 20% testing split
wf_training = wf[:int(len(wf) * 0.8)]
wf_testing = wf[int(len(wf) * 0.8):]

In [69]:
wf_testing.reset_index(inplace=True)
wf_testing.drop('index', axis=1, inplace=True)
wf_testing

/tmp/ipykernel_1192/3894747268.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wf_testing.drop('index', axis=1, inplace=True)

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,2008-07-05 00:00:00,Dmitry Medvedev,Speech at Inauguration Ceremony as President o...,citizens russia friends sworn presidential oat...,President,Dmitry Medvedev,http://en.kremlin.ru/events/president/transcri...,1,OTHERS
1,USA,19/10/2013,Barack Obama,\nWeekly Address: Working Together on Behalf o...,hi everybody week democrats responsible republ...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,0,DEVELOPMENT
2,USA,13/08/2016,Barack Obama,"\nWeekly Address: Providing a Better, Cleaner,...",hi everybody one urgent challenges time climat...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,DEVELOPMENT
3,Russia,26-07-2001,Vladimir Putin,Opening Remarks at a Security Council Meeting ...,good afternoon today scheduled discuss develop...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,2,DEVELOPMENT
4,USA,2021-03-18 00:00:00,Joe Biden,Statement by President Biden on the Farm Workf...,farmworkers vital wellbeing country economy ge...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,1,OTHERS
...,...,...,...,...,...,...,...,...,...,...
397,China,2016-06-20 00:00:00,H.E. Wang Yi,Build a New Type of International Relations Fe...,march 2013 visit russia general secretary xi j...,State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,1,INTERNATIONAL AFFAIRS
398,China,2020-09-08 00:00:00,H.E. Wang Yi,"Upholding Multilateralism, Fairness and Justic...",distinguished guests colleagues ladies gentlem...,State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,0,DEVELOPMENT
399,United Kingdom,19 July 2011,David Cameron,"PM's speech on aid, trade and democracy",today eyes world another part continent somali...,Prime Minister,David Cameron,https://www.gov.uk/government/speeches/pms-spe...,1,DEVELOPMENT
400,Russia,26-10-2017,Vladimir Putin,Security Council meeting,good afternoon colleagues today discuss set is...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,DEVELOPMENT
401,China,2020-09-03 00:00:00,H.E. Wang Yi,Strengthening Cooperation to Weather the Tryin...,highness prince faisal bin farhan al saud coll...,State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,0,DEVELOPMENT

In [70]:
wf_training.reset_index(inplace=True)
wf_training.drop('index', axis=1, inplace=True)
wf_training

/tmp/ipykernel_1192/1694703126.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wf_training.drop('index', axis=1, inplace=True)

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,2002-08-07 00:00:00,Vladimir Putin,Extracts from Opening Remarks at a Security Co...,good afternoon today discussing economic aspec...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,DEVELOPMENT
1,USA,2021-09-02 00:00:00,Joe Biden,Remarks by President Biden in Virtual Call for...,president well thank much start bit apology vi...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,0,OTHERS
2,Russia,24-12-2007,Vladimir Putin,Speech at the Opening Ceremony for the Year of...,dear friends days leading christmas new year h...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,OTHERS
3,USA,15/12/2015,Barack Obama,\nRemarks by the President at Naturalization C...,well good morning everybody thank deputy secre...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,NATIONALISM
4,Russia,2005-09-11 00:00:00,Vladimir Putin,Closing Remarks at Meeting with the Armed Forc...,would like say words heard defence minister’s ...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,OTHERS
...,...,...,...,...,...,...,...,...,...,...
1603,USA,2021-08-10 00:00:00,Joe Biden,Remarks by President Biden Before a Briefing f...,president hey folks i’ll make brief opening st...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,0,OTHERS
1604,United Kingdom,16 January 2016,Theresa May,PM's statement at Downing Street: 16 January 2019,evening government confidence parliament gives...,Prime Minister,Theresa May,https://www.gov.uk/government/speeches/pms-sta...,1,OTHERS
1605,Russia,27-02-2002,Vladimir Putin,Introductory Remarks at a Security Council Mee...,good afternoon agenda includes situation chech...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,2,DEVELOPMENT
1606,United Kingdom,1 September 2011,David Cameron,PM's press conference in Paris,thank nicolas thank way organised conference t...,Prime Minister,David Cameron,https://www.gov.uk/government/speeches/pms-pre...,1,INTERNATIONAL AFFAIRS
1607,USA,2021-10-28 00:00:00,Joe Biden,"Statement by President Joseph R. Biden, Jr. on...",leaders organizations around world including a...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,2,INTERNATIONAL AFFAIRS

In [71]:
wf_training

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,2002-08-07 00:00:00,Vladimir Putin,Extracts from Opening Remarks at a Security Co...,good afternoon today discussing economic aspec...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,DEVELOPMENT
1,USA,2021-09-02 00:00:00,Joe Biden,Remarks by President Biden in Virtual Call for...,president well thank much start bit apology vi...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,0,OTHERS
2,Russia,24-12-2007,Vladimir Putin,Speech at the Opening Ceremony for the Year of...,dear friends days leading christmas new year h...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,OTHERS
3,USA,15/12/2015,Barack Obama,\nRemarks by the President at Naturalization C...,well good morning everybody thank deputy secre...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,NATIONALISM
4,Russia,2005-09-11 00:00:00,Vladimir Putin,Closing Remarks at Meeting with the Armed Forc...,would like say words heard defence minister’s ...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,OTHERS
...,...,...,...,...,...,...,...,...,...,...
1603,USA,2021-08-10 00:00:00,Joe Biden,Remarks by President Biden Before a Briefing f...,president hey folks i’ll make brief opening st...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,0,OTHERS
1604,United Kingdom,16 January 2016,Theresa May,PM's statement at Downing Street: 16 January 2019,evening government confidence parliament gives...,Prime Minister,Theresa May,https://www.gov.uk/government/speeches/pms-sta...,1,OTHERS
1605,Russia,27-02-2002,Vladimir Putin,Introductory Remarks at a Security Council Mee...,good afternoon agenda includes situation chech...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,2,DEVELOPMENT
1606,United Kingdom,1 September 2011,David Cameron,PM's press conference in Paris,thank nicolas thank way organised conference t...,Prime Minister,David Cameron,https://www.gov.uk/government/speeches/pms-pre...,1,INTERNATIONAL AFFAIRS
1607,USA,2021-10-28 00:00:00,Joe Biden,"Statement by President Joseph R. Biden, Jr. on...",leaders organizations around world including a...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,2,INTERNATIONAL AFFAIRS

In [72]:
training_sentences = wf_training.Text_of_Speech.to_numpy()
#training labels
training_labels = wf_training.Emotion.to_numpy()

validation_sentences = wf_testing.Text_of_Speech.to_numpy()
#training labels
validation_labels = wf_testing.Emotion.to_numpy()

In [73]:
training_sentences.shape, validation_sentences.shape

((1608,), (402,))

In [74]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=num_unique_words)
tokenizer.fit_on_texts(training_sentences)

In [75]:
word_index = tokenizer.word_index

In [76]:
training_sequences = tokenizer.texts_to_sequences(training_sentences)
validation_sequences = tokenizer.texts_to_sequences(validation_sentences)

In [77]:
#padding sequences to have the same length
from tensorflow.keras.preprocessing.sequence import pad_sequences

#max number of words per sequence
max_length = 500

training_padded = pad_sequences(training_sequences, maxlen=max_length, padding="post", truncating="post")
validation_padded = pad_sequences(validation_sequences, maxlen=max_length, padding="post", truncating="post")
training_padded.shape, validation_padded.shape

((1608, 500), (402, 500))

In [78]:
print(num_unique_words)

38938

In [79]:
#LSTM Model
import tensorflow.keras as keras


#embedding layer converts the words into vectors of fixed size
#dropout rate drops out a certain percentage of input data so that the
#model learns more robust ways of learning and does not overfit
model = keras.models.Sequential()
model.add(layers.Embedding(num_unique_words, 32))
model.add(layers.Bidirectional(layers.LSTM(64, dropout=0.2, recurrent_dropout=0.2)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(3, activation='softmax'))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [80]:
loss = 'sparse_categorical_crossentropy'
optim = keras.optimizers.Adam(learning_rate=0.001) #from 0.001
metrics = ["accuracy"]

model.compile(loss=loss, optimizer=optim, metrics=metrics)

In [81]:
print(training_padded.dtype, training_padded.shape)

int32 (1608, 500)

In [82]:
training_labels = np.array(training_labels).astype(np.int64)
validation_labels = np.array(validation_labels).astype(np.int64)

In [83]:
print(training_padded.dtype, training_padded.shape)
print(training_labels.dtype, training_labels.shape)

int32 (1608, 500)
int64 (1608,)

In [84]:
print(training_padded)

[[   46   662    14 ...     0     0     0]
 [   60    57    18 ...  1601   695  2915]
 [  295   129   276 ...     0     0     0]
 ...
 [   46   662   424 ...     0     0     0]
 [   18 11185    18 ...     0     0     0]
 [  162   709   103 ...     0     0     0]]

In [85]:
print(counter)

Counter({'people': 9977, '—': 8222, 'new': 6587, 'world': 6530, 'work': 6325, 'us': 6261, 'china': 6246, 'countries': 6156, 'development': 6030, 'one': 5367, 'also': 5297, 'country': 5190, 'cooperation': 5139, 'today': 4997, 'need': 4856, 'make': 4751, 'thank': 4400, 'years': 4319, 'like': 4236, 'must': 4210, 'going': 4136, 'want': 4067, 'know': 4061, 'would': 3998, 'it’s': 3995, 'time': 3944, 'international': 3876, 'economic': 3761, 'many': 3709, 'applause': 3698, 'first': 3525, 'we’re': 3520, '–': 3500, 'year': 3467, 'security': 3461, 'united': 3394, 'economy': 3278, 'states': 3250, 'that’s': 3248, 'every': 3222, 'great': 3150, 'important': 3121, 'get': 3113, 'together': 3081, 'american': 3075, 'good': 2925, 'government': 2885, 'way': 2808, 'much': 2796, 'america': 2769, 'support': 2767, 'state': 2744, 'right': 2705, 'global': 2697, 'take': 2653, 'help': 2564, 'well': 2558, 'president': 2520, 'think': 2490, 'two': 2466, 'future': 2365, 'system': 2354, 'national': 2342, 'made': 2333, 'even': 2319, 'russia': 2247, 'law': 2237, 'last': 2180, 'continue': 2167, 'say': 2143, 'we’ve': 2136, 'working': 2110, 'back': 2108, 'growth': 2096, 'chinese': 2063, 'see': 2031, 'peace': 2019, 'americans': 2013, 'trade': 1987, 'said': 1972, 'jobs': 1960, 'better': 1931, 'come': 1918, 'part': 1885, 'still': 1869, 'day': 1800, 'families': 1777, 'including': 1768, 'community': 1750, 'got': 1749, 'business': 1730, 'nation': 1716, 'efforts': 1705, 'build': 1701, 'sure': 1693, 'already': 1687, 'i’m': 1677, 'russian': 1674, 'around': 1650, 'keep': 1650, 'course': 1639, 'progress': 1631, 'let': 1629, 'lives': 1628, 'common': 1627, 'done': 1609, 'health': 1595, 'could': 1594, 'long': 1581, 'life': 1581, 'never': 1568, 'relations': 1521, 'across': 1519, 'political': 1517, 'put': 1516, 'interests': 1513, 'go': 1507, 'place': 1503, 'million': 1487, 'war': 1486, 'history': 1486, 'military': 1485, 'past': 1484, 'may': 1482, 'public': 1473, 'always': 1466, 'regional': 1466, 'nations': 1463, 'social': 1457, 'making': 1447, 'believe': 1432, 'number': 1422, 'change': 1413, 'friends': 1409, 'give': 1402, 'don’t': 1390, 'problems': 1373, 'issues': 1373, 'things': 1364, 'region': 1364, 'investment': 1363, 'job': 1351, 'open': 1346, 'ago': 1339, 'federal': 1334, 'care': 1331, 'hope': 1327, 'lot': 1325, 'situation': 1303, 'forward': 1303, 'set': 1301, 'energy': 1299, 'look': 1298, 'able': 1284, 'end': 1281, 'leaders': 1278, 'home': 1277, 'use': 1274, 'since': 1271, 'next': 1270, 'percent': 1266, 'children': 1255, 'education': 1255, 'citizens': 1251, 'plan': 1244, 'chinas': 1237, 'best': 1236, 'rights': 1232, 'means': 1227, 'they’re': 1226, 'everybody': 1204, 'developing': 1204, 'power': 1196, 'building': 1195, 'ensure': 1192, 'women': 1179, 'major': 1178, 'create': 1176, 'policy': 1169, 'another': 1168, 'ever': 1168, 'clear': 1167, 'foreign': 1165, 'without': 1163, 'possible': 1162, 'congress': 1158, 'strong': 1156, 'meeting': 1153, 'reform': 1144, 'second': 1134, 'society': 1133, 'order': 1129, 'members': 1129, 'businesses': 1128, 'something': 1125, 'hard': 1123, 'areas': 1115, 'different': 1115, 'act': 1112, 'opportunity': 1110, 'free': 1110, 'financial': 1103, 'issue': 1102, 'young': 1100, 'human': 1098, 'africa': 1094, 'three': 1083, 'laughter': 1082, 'times': 1081, 'service': 1079, 'forces': 1074, 'companies': 1065, 'market': 1059, 'big': 1054, 'local': 1049, 'protect': 1046, 'billion': 1045, 'far': 1041, 'workers': 1028, 'family': 1027, 'regions': 1025, 'challenges': 1025, 'others': 1015, 'whole': 1013, 'measures': 1008, 'infrastructure': 1002, 'nuclear': 995, 'road': 993, 'colleagues': 993, 'level': 992, 'respect': 988, 'un': 988, 'general': 986, 'pay': 986, 'provide': 985, 'mutual': 983, 'shared': 979, 'i’ve': 976, 'become': 967, 'council': 958, 'everyone': 955, 'role': 955, 'cannot': 947, 'thing': 945, 'really': 945, 'fight': 937, 'fact': 936, 'special': 932, 'you’re': 932, 'stand': 920, 'needs': 919, 'bring': 918, 'everything': 911, 'resources': 907, 'process': 906, 'god': 904, 'promote': 901, 'increase': 898, 'taking': 896, 'greater': 895, 'stability': 893, 'crisis': 892, 'taken': 887, 'action': 885, 'share': 884, 'real': 884, 'high': 880, 'effective': 876, 'necessary': 875, 'communities': 875, 'deal': 873, 'seen': 872, 'tax': 864, 'peoples': 862, 'climate': 855, 'services': 847, 'force': 847, 'among': 840, 'full': 839, 'opportunities': 839, 'days': 836, 'live': 833, 'partners': 832, 'ready': 822, 'improve': 817, 'there’s': 812, 'start': 811, 'achieve': 809, 'justice': 808, 'prosperity': 804, 'point': 803, 'europe': 800, 'sector': 797, 'parties': 787, 'asia': 785, 'house': 780, 'money': 780, 'months': 778, 'folks': 778, 'meet': 776, 'millions': 775, 'potential': 774, 'strengthen': 764, 'summit': 760, 'step': 758, 'responsibility': 756, 'projects': 755, 'five': 754, 'mr': 754, 'partnership': 753, 'attention': 750, 'coming': 750, 'freedom': 749, 'face': 748, 'technology': 748, 'african': 740, 'address': 738, 'example': 737, 'strategic': 736, 'within': 732, 'problem': 732, 'dear': 731, 'ahead': 730, 'thanks': 728, 'middle': 728, 'innovation': 725, 'getting': 724, 'success': 722, 'yet': 720, 'principles': 718, 'men': 715, 'conditions': 712, 'took': 705, 'especially': 704, 'remember': 703, 'east': 702, 'school': 701, 'committed': 701, 'approach': 700, 'proud': 699, 'entire': 699, 'week': 698, 'key': 697, 'joint': 695, 'love': 693, 'area': 692, 'understand': 691, 'single': 689, 'secretary': 684, 'fully': 684, 'democracy': 682, 'third': 681, 'find': 679, 'afghanistan': 675, 'true': 674, 'modern': 674, 'information': 671, 'office': 670, 'growing': 667, 'terrorism': 665, 'agreement': 664, 'develop': 662, 'commitment': 662, 'less': 657, 'matter': 653, 'minister': 652, 'schools': 651, 'small': 649, 'decades': 648, 'we’ll': 647, 'steps': 645, 'tell': 643, 'rules': 643, 'values': 642, 'civil': 641, 'given': 641, 'moment': 640, 'enforcement': 638, 'often': 636, 'budget': 636, 'task': 635, 'initiative': 635, 'european': 634, 'chance': 633, 'came': 630, 'difficult': 629, 'actions': 628, 'kind': 628, 'union': 628, 'safe': 626, 'administration': 626, 'quality': 622, 'control': 622, 'friendship': 621, 'century': 618, 'results': 617, 'honor': 616, 'incredible': 616, 'fair': 614, 'can’t': 613, 'benefits': 613, 'decisions': 613, 'peaceful': 613, 'south': 612, 'close': 611, 'spirit': 608, 'environment': 608, 'lead': 606, 'leadership': 605, 'dialogue': 603, 'enough': 601, 'path': 601, 'rate': 600, 'effort': 600, 'wish': 597, 'used': 596, 'whether': 596, 'poverty': 594, 'finally': 592, 'mean': 592, 'four': 591, 'turn': 587, 'stronger': 587, 'move': 587, 'worked': 586, 'sustainable': 586, 'based': 583, 'focus': 583, 'laws': 582, 'access': 581, 'police': 581, 'changes': 580, 'covid19': 580, 'virus': 580, 'veterans': 580, 'agenda': 579, 'ways': 578, 'main': 577, 'call': 577, 'thousands': 576, 'little': 576, 'along': 575, 'experience': 575, 'threat': 575, 'bless': 570, 'welcome': 568, 'words': 568, 'makes': 567, 'priority': 566, 'goal': 564, 'capacity': 559, 'remain': 559, 'nearly': 559, 'half': 557, 'created': 555, 'violence': 554, 'ask': 554, 'benefit': 551, 'play': 550, 'lost': 549, 'serious': 549, 'sense': 545, 'stop': 545, 'higher': 545, 'advance': 544, 'helping': 543, 'stay': 541, 'prime': 540, 'uk': 540, 'exchanges': 540, 'living': 539, 'particular': 538, 'talk': 536, 'science': 536, 'simply': 536, 'current': 535, 'trust': 534, 'legal': 534, 'threats': 532, 'ones': 531, 'basis': 530, 'line': 527, 'various': 525, 'recent': 524, 'authorities': 524, 'weeks': 523, 'uphold': 523, 'serve': 521, 'nothing': 520, 'strength': 520, 'allow': 518, 'terrorist': 518, 'governance': 518, 'you’ve': 517, 'longterm': 517, 'students': 517, 'early': 516, 'fighting': 515, 'join': 515, 'comprehensive': 513, 'reason': 512, 'party': 512, 'almost': 511, 'groups': 511, 'agencies': 510, 'behind': 509, 'responsible': 508, 'helped': 507, 'strategy': 506, 'grow': 506, 'winwin': 506, 'gentlemen': 503, 'away': 502, 'old': 502, 'plans': 502, 'xi': 502, 'discuss': 501, 'assistance': 499, 'generation': 498, 'training': 496, 'britain': 496, 'let’s': 495, 'bill': 495, 'pursue': 494, 'border': 493, 'remains': 493, 'ladies': 493, 'actually': 493, 'industrial': 493, 'standards': 492, 'ministry': 492, 'safety': 491, 'industry': 490, 'creating': 490, 'thats': 490, 'institutions': 487, 'relationship': 487, 'called': 485, 'month': 484, 'top': 484, 'large': 483, 'basic': 482, 'positive': 481, 'forum': 480, 'vision': 480, 'built': 478, 'russia’s': 477, 'visit': 476, 'city': 476, 'hold': 475, 'cases': 475, 'culture': 474, 'asean': 474, 'central': 473, 'america’s': 473, 'speak': 473, 'armed': 472, 'country’s': 471, 'prevent': 471, 'cut': 471, 'private': 470, 'research': 469, 'enhance': 467, 'belt': 467, 'victory': 467, 'several': 466, 'looking': 466, 'following': 464, 'eu': 464, 'north': 463, 'met': 462, 'developed': 462, 'production': 462, 'resolve': 461, 'challenge': 460, 'space': 459, 'case': 457, 'significant': 457, 'protection': 456, 'active': 456, 'largest': 455, 'beyond': 454, 'follow': 454, 'held': 453, 'ideas': 453, 'class': 452, 'goals': 451, 'faith': 451, 'response': 451, 'signed': 450, 'terrorists': 450, 'pandemic': 449, 'anniversary': 449, 'housing': 447, 'happen': 447, 'ground': 447, 'involved': 445, 'expand': 445, 'position': 445, 'truly': 445, 'passed': 444, 'soon': 443, 'save': 443, 'markets': 443, 'raise': 442, 'feel': 442, 'economies': 442, 'asian': 442, 'deliver': 442, 'leading': 440, 'least': 440, 'sides': 439, 'result': 438, 'land': 435, 'recovery': 434, 'saying': 433, 'weapons': 433, 'leave': 433, 'interest': 433, 'seek': 430, 'legislation': 430, 'certain': 430, 'medical': 429, 'fundamental': 428, 'foundation': 428, 'decision': 427, 'events': 427, 'reduce': 426, 'coordination': 426, 'troops': 425, 'equal': 424, 'vital': 424, 'question': 424, 'member': 423, 'begin': 422, 'brought': 422, 'left': 421, 'however': 420, 'group': 418, 'present': 417, 'mission': 416, 'cities': 416, 'tasks': 416, 'choice': 416, 'isil': 416, 'historic': 416, 'what’s': 415, 'child': 415, 'syria': 415, 'affairs': 414, 'jointly': 414, 'comes': 412, 'rest': 412, 'idea': 411, 'trying': 411, 'might': 411, 'six': 411, 'domestic': 410, 'courage': 410, 'hear': 409, 'systems': 408, 'dollars': 408, 'policies': 408, 'officers': 407, 'confidence': 406, 'insurance': 405, 'representatives': 405, 'needed': 405, 'relevant': 404, 'carry': 404, 'iraq': 404, 'contribution': 404, 'reach': 403, 'secure': 403, 'overall': 403, 'extraordinary': 403, 'afternoon': 402, '10': 402, 'agree': 402, 'critical': 402, 'cost': 402, 'period': 401, 'personnel': 401, 'show': 400, 'talking': 400, 'actively': 400, 'man': 399, 'they’ve': 399, 'happened': 397, 'please': 397, 'importance': 396, 'cultural': 395, 'therefore': 395, 'rather': 394, 'democratic': 394, 'terms': 394, 'dignity': 393, 'heard': 393, 'technologies': 393, 'heart': 391, 'federation': 391, 'goods': 389, 'manufacturing': 389, 'towards': 388, 'diplomacy': 387, 'iran': 386, 'organizations': 385, 'sometimes': 385, 'vote': 384, 'kids': 384, 'drug': 384, 'equipment': 384, 'instead': 383, 'risk': 381, 'demand': 381, 'yesterday': 381, 'doesn’t': 379, 'affordable': 379, 'diplomatic': 379, 'criminal': 379, 'levels': 379, 'green': 378, 'alone': 377, 'framework': 376, 'huge': 376, 'executive': 375, 'longer': 375, 'particularly': 375, 'heads': 375, 'fellow': 374, 'supply': 374, 'implement': 373, 'recently': 373, 'biggest': 373, '100': 373, 'republicans': 373, 'speaker': 373, 'view': 372, 'crime': 372, 'ensuring': 371, '50': 371, 'allies': 371, 'increasing': 370, 'side': 370, 'stage': 370, 'white': 369, 'beautiful': 369, 'stable': 369, '20': 368, 'team': 367, 'weve': 367, 'invest': 365, 'agreed': 365, 'goes': 365, 'saw': 364, 'investments': 364, 'british': 364, 'absolutely': 363, 'rule': 363, 'promoting': 363, 'story': 362, 'understanding': 362, 'paid': 362, 'beginning': 362, 'people’s': 362, 'greatest': 362, 'throughout': 361, 'achieved': 361, 'places': 360, 'improving': 359, 'hand': 359, 'activities': 359, 'didn’t': 358, 'republic': 358, 'jinping': 358, 'encourage': 358, 'spread': 357, 'told': 356, 'toward': 356, 'additional': 356, 'went': 355, 'stress': 354, 'works': 354, 'capital': 353, 'defence': 353, 'conflict': 353, 'governments': 353, 'started': 352, 'maintain': 351, 'department': 351, 'integration': 351, 'try': 351, 'implementation': 350, 'fourth': 349, 'exchange': 349, 'effectively': 349, 'costs': 349, 'internet': 349, 'directly': 348, 'draw': 348, 'though': 348, 'sea': 348, 'morning': 347, 'impact': 346, 'thought': 346, 'independent': 346, 'asiapacific': 346, 'opening': 345, 'successful': 345, 'majority': 344, 'facing': 344, 'humanitarian': 344, 'pass': 344, 'faster': 344, 'person': 343, 'direct': 343, 'nhs': 343, 'fund': 341, 'gave': 341, 'politics': 340, 'increased': 340, 'moving': 340, 'regime': 339, 'immigration': 338, 'practical': 338, 'differences': 338, 'contribute': 337, 'duty': 337, 'mind': 336, 'despite': 336, 'reached': 336, 'natural': 336, 'ultimately': 336, 'conference': 335, 'tough': 335, 'election': 335, 'proposals': 334, 'mechanisms': 333, 'happy': 333, 'air': 333, 'partner': 333, 'clean': 333, 'disease': 332, 'population': 332, 'starting': 331, 'ability': 331, 'i’ll': 330, 'account': 330, 'inclusive': 329, 'loved': 328, 'generations': 328, 'west': 328, 'confident': 328, 'vaccine': 328, 'competition': 328, 'funding': 328, 'today’s': 327, 'wages': 327, 'offer': 327, 'college': 327, 'hands': 327, 'deepen': 326, 'products': 326, 'quickly': 325, 'protecting': 324, 'wanted': 324, 'truth': 324, 'upon': 324, 'indeed': 324, 'army': 324, 'water': 324, 'else': 323, 'defend': 323, 'media': 323, 'principle': 323, 'discussion': 322, 'anything': 322, 'announced': 322, 'using': 322, 'transport': 321, 'program': 321, 'behalf': 321, '1': 321, 'unity': 321, 'he’s': 320, 'lower': 320, 'joined': 320, 'sco': 320, 'defense': 319, 'programme': 319, 'outstanding': 319, 'cause': 318, 'data': 318, 'model': 318, 'parents': 317, 'concerns': 317, 'world’s': 317, 'ties': 317, 'closely': 317, 'whose': 316, 'bilateral': 316, 'discussed': 316, 'unemployment': 315, 'willing': 314, 'expect': 314, 'gives': 313, 'fought': 313, 'quite': 313, 'later': 312, 'hundreds': 311, 'providing': 311, 'dangerous': 311, 'per': 310, 'strengthening': 310, 'form': 309, 'food': 308, 'seeing': 308, 'rise': 308, 'debt': 307, 'washington': 307, 'known': 306, 'giving': 306, 'firmly': 306, 'mankind': 306, 'promise': 305, 'priorities': 305, 'boost': 305, 'risks': 304, 'operations': 304, 'happening': 304, 'religious': 304, 'industries': 304, 'scientific': 303, 'vaccines': 302, 'g20': 302, 'spending': 300, 'neighbors': 300, 'direction': 300, 'value': 299, 'agreements': 299, 'construction': 299, 'environmental': 299, 'message': 298, 'includes': 298, 'unfortunately': 298, 'multilateral': 298, 'practice': 298, 'friend': 297, 'gone': 297, 'forget': 297, 'room': 297, 'officials': 297, 'total': 297, 'simple': 295, 'nature': 295, 'supporting': 295, 'easy': 294, 'advanced': 294, 'closer': 293, 'tremendous': 293, 'anyone': 293, 'organisations': 293, 'attack': 292, 'india': 292, 'average': 291, 'emergency': 290, 'return': 290, 'asked': 289, 'staff': 289, 'parts': 289, 'yes': 288, 'sectors': 288, 'reforms': 288, 'project': 287, '15': 286, 'gas': 285, 'requires': 285, 'powerful': 285, 'putting': 285, 'abroad': 285, 'borders': 284, 'keeping': 284, 'appreciate': 284, 'fast': 284, 'effect': 283, 'news': 283, 'earlier': 283, 'provided': 282, 'seven': 282, 'achievements': 282, 'learn': 281, 'age': 281, 'wrong': 281, 'establish': 281, 'established': 281, 'attacks': 280, 'dream': 280, 'universities': 280, 'specific': 280, 'range': 280, 'initiatives': 280, 'hearts': 279, 'field': 279, 'corruption': 279, 'responsibilities': 278, 'silk': 278, 'trend': 278, 'grateful': 278, 'difficulties': 278, 'campaign': 277, 'decade': 277, 'individual': 276, 'paying': 276, 'equality': 276, 'financing': 276, 'found': 275, 'available': 275, 'governor': 275, 'moscow': 275, 'constitution': 275, 'heroes': 275, 'independence': 274, 'spent': 273, 'senate': 273, 'record': 273, 'oil': 273, 'aid': 273, 'prepared': 272, 'traditional': 272, 'taxes': 272, '21st': 271, 'night': 271, 'personal': 270, 'won’t': 270, 'bringing': 270, 'changing': 270, 'speed': 270, 'treaty': 270, 'clearly': 269, 'report': 269, 'healthcare': 269, 'learning': 269, '40': 268, 'sphere': 268, 'openingup': 268, 'competitive': 268, 'continues': 267, 'note': 267, 'determined': 267, 'chinaafrica': 267, 'unique': 266, 'test': 266, 'difference': 266, 'sound': 266, 'spoke': 264, 'essential': 264, 'front': 264, '30': 264, 'court': 264, 'operation': 264, 'crimes': 263, 'consider': 263, 'continued': 263, 'conclusion': 263, 'aware': 262, 'due': 262, 'homes': 261, 'importantly': 261, 'consensus': 261, 'outside': 261, 'sacrifice': 261, 'consultation': 261, 'led': 260, 'pursuing': 260, 'innovative': 260, 'complete': 259, 'sovereignty': 259, 'bank': 259, 'thinking': 259, 'humanity': 259, 'questions': 258, 'standing': 257, 'takes': 257, 'drugs': 257, 'complex': 257, 'steady': 257, 'win': 257, 'obviously': 257, 'programmes': 256, 'certainly': 256, 'run': 256, 'historical': 256, 'connectivity': 256, 'negotiations': 256, 'civilizations': 256, 'enormous': 255, 'scale': 255, 'easier': 255, 'cuts': 254, 'trillion': 254, 'facilities': 253, 'teachers': 253, 'powers': 253, 'pressure': 253, 'nato': 253, 'organization': 253, 'center': 252, 'vaccinated': 252, 'adopted': 252, 'balanced': 252, 'earth': 252, 'final': 251, 'solution': 251, 'supported': 251, 'whatever': 251, 'nobody': 251, 'combat': 250, 'multilateralism': 250, 'sign': 249, 'core': 249, 'vast': 249, 'focused': 249, 'prosperous': 249, 'crucial': 249, 'john': 248, 'leader': 248, 'subject': 248, 'foster': 247, 'receive': 247, 'founding': 247, 'authority': 247, 'apec': 247, 'shows': 246, 'tomorrow': 246, 'meetings': 246, 'solidarity': 246, 'killed': 245, 'purpose': 245, 'solve': 245, 'presidential': 245, 'distinguished': 244, 'thus': 244, 'profound': 244, 'celebrate': 243, 'deserve': 243, 'technological': 243, 'drive': 243, 'forms': 241, 'served': 240, 'mechanism': 240, 'express': 240, 'prices': 240, 'skills': 240, 'deeply': 239, 'event': 239, 'experts': 239, 'company': 239, 'settlement': 239, 'assembly': 238, 'short': 238, 'management': 238, 'respond': 238, 'reality': 238, 'proposed': 237, 'send': 237, 'treatment': 237, 'duma': 237, 'matters': 236, 'repeat': 236, 'coalition': 236, 'ukraine': 236, 'stands': 236, 'concerned': 236, 'rescue': 235, 'democrats': 235, 'bipartisan': 235, 'extremism': 235, 'emerging': 235, 'participation': 235, 'charter': 235, 'momentum': 235, 'internal': 234, 'organisation': 234, 'collective': 234, 'bigger': 234, 'recognize': 234, 'require': 234, 'era': 234, 'received': 233, 'existing': 233, 'individuals': 233, '70': 232, 'peninsula': 232, 'amount': 231, 'battle': 231, 'openness': 231, 'brics': 230, 'began': 229, 'doubt': 229, 'shot': 229, 'korean': 229, 'reasons': 229, 'buy': 229, 'fire': 229, 'changed': 228, 'bodies': 228, 'mass': 228, 'head': 228, 'nation’s': 228, 'highest': 228, 'ten': 228, 'succeed': 228, 'professional': 228, 'according': 228, 'digital': 228, 'trading': 228, 'funds': 228, 'rates': 227, 'structure': 227, 'serving': 227, 'solid': 227, 'bad': 226, 'concrete': 226, 'gun': 226, 'light': 225, 'fear': 225, 'conflicts': 225, 'gdp': 225, 'wonderful': 225, 'creation': 224, 'sent': 224, 'credit': 224, 'influence': 224, 'properly': 224, 'rural': 223, 'income': 223, 'addition': 223, 'programs': 223, 'choose': 223, 'commitments': 223, 'roads': 223, 'deep': 222, 'review': 222, 'launched': 222, 'carried': 222, 'bit': 221, 'price': 221, 'highly': 220, 'break': 220, 'deficit': 220, '2020': 220, 'vice': 219, 'faced': 219, 'rising': 219, 'statement': 219, 'guests': 219, 'discussions': 219, 'covid': 218, 'extremely': 218, 'spend': 218, 'soldiers': 217, 'although': 217, 'host': 216, 'hit': 216, 'realize': 215, 'arms': 215, 'became': 214, 'asking': 214, 'victim

In [86]:
##making sure that overrepresentation of a class does not affect the model
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(training_labels),
    y=training_labels
)
class_weights = dict(enumerate(class_weights))

In [87]:
class_weights

{0: 1.1452991452991452, 1: 0.6042841037204059, 2: 2.1185770750988144}

In [ ]:
model.fit(training_padded, training_labels, epochs=10, validation_data=(validation_padded, validation_labels), class_weight=class_weights, batch_size=32, verbose=2)

Epoch 1/10

# Adding in L2 Regularization and Dropout to the Model to Prevent Overfitting

In [ ]:
#LSTM Model

from tensorflow.keras import regularizers


#embedding layer converts the words into vectors of fixed size
#dropout rate drops out a certain percentage of input data so that the
#model learns more robust ways of learning and does not overfit
#l2 regularization is used to prevent large weights from being learned, and thus less overfitting

model = keras.models.Sequential()
model.add(layers.Embedding(num_unique_words, 32))
model.add(layers.Bidirectional(layers.LSTM(64, dropout=0.4, recurrent_dropout=0.4)))
model.add(layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(layers.Dense(3, activation='softmax'))
model.summary()



loss = 'sparse_categorical_crossentropy'
optim = keras.optimizers.Adam(learning_rate=0.001) #from 0.001
metrics = ["accuracy"]

model.compile(loss=loss, optimizer=optim, metrics=metrics)


model.fit(training_padded, training_labels, epochs=20, validation_data=(validation_padded, validation_labels), class_weight=class_weights, batch_size=32, verbose=2)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
51/51 - 169s - 3s/step - accuracy: 0.3893 - loss: 1.2478 - val_accuracy: 0.2438 - val_loss: 1.2153
Epoch 2/20
51/51 - 168s - 3s/step - accuracy: 0.2780 - loss: 1.1645 - val_accuracy: 0.4652 - val_loss: 1.1026
Epoch 3/20
51/51 - 164s - 3s/step - accuracy: 0.4353 - loss: 1.0656 - val_accuracy: 0.5124 - val_loss: 1.0026
Epoch 4/20
51/51 - 169s - 3s/step - accuracy: 0.5889 - loss: 0.8508 - val_accuracy: 0.6095 - val_loss: 0.9325
Epoch 5/20
51/51 - 165s - 3s/step - accuracy: 0.6891 - loss: 0.7052 - val_accuracy: 0.5771 - val_loss: 1.0177
Epoch 6/20
51/51 - 166s - 3s/step - accuracy: 0.7711 - loss: 0.5706 - val_accuracy: 0.5224 - val_loss: 1.1491
Epoch 7/20
51/51 - 169s - 3s/step - accuracy: 0.8296 - loss: 0.4387 - val_accuracy: 0.4428 - val_loss: 1.3453
Epoch 8/20
51/51 - 168s - 3s/step - accuracy: 0.8738 - loss: 0.3641 - val_accuracy: 0.4751 - val_loss: 1.5363
Epoch 9/20
51/51 - 166s - 3s/step - accuracy: 0.8775 - loss: 0.3509 - val_accuracy: 0.5050 - val_loss: 1.2408
Epoch 10/20
51/51 - 168s - 3s/step - accuracy: 0.9241 - loss: 0.2581 - val_accuracy: 0.4900 - val_loss: 1.5099
Epoch 11/20
51/51 - 168s - 3s/step - accuracy: 0.9391 - loss: 0.2033 - val_accuracy: 0.4602 - val_loss: 1.6720
Epoch 12/20
51/51 - 167s - 3s/step - accuracy: 0.9552 - loss: 0.1858 - val_accuracy: 0.4726 - val_loss: 1.7897
Epoch 13/20
51/51 - 174s - 3s/step - accuracy: 0.9602 - loss: 0.1631 - val_accuracy: 0.4602 - val_loss: 1.9278
Epoch 14/20
51/51 - 173s - 3s/step - accuracy: 0.9677 - loss: 0.1399 - val_accuracy: 0.4876 - val_loss: 1.9891
Epoch 15/20
51/51 - 174s - 3s/step - accuracy: 0.9621 - loss: 0.1502 - val_accuracy: 0.4652 - val_loss: 2.0447
Epoch 16/20
51/51 - 172s - 3s/step - accuracy: 0.9739 - loss: 0.1321 - val_accuracy: 0.4627 - val_loss: 2.1954
Epoch 17/20
51/51 - 164s - 3s/step - accuracy: 0.9782 - loss: 0.1220 - val_accuracy: 0.3930 - val_loss: 2.3014
Epoch 18/20
51/51 - 161s - 3s/step - accuracy: 0.9670 - loss: 0.1261 - val_accuracy: 0.4776 - val_loss: 2.0705
Epoch 19/20
51/51 - 163s - 3s/step - accuracy: 0.9863 - loss: 0.1020 - val_accuracy: 0.4229 - val_loss: 2.1638
Epoch 20/20
51/51 - 166s - 3s/step - accuracy: 0.9813 - loss: 0.0971 - val_accuracy: 0.4204 - val_loss: 2.3902

# Adding Bayesian Optimization For Hyperparameter Tuning

In [ ]:
def build_model(hp):
    model = keras.models.Sequential()
    model.add(layers.Embedding(num_unique_words, hp.Choice('embedding_dim', [32, 64, 128])))
    model.add(layers.Bidirectional(layers.LSTM(hp.Int('lstm_units', 32, 256, step=32), dropout=hp.Choice('dropout', [0.2, 0.3, 0.4, 0.5]), recurrent_dropout=hp.Choice('recurrent_dropout', [0.2, 0.3, 0.4, 0.5])))
    model.add(layers.Dense(hp.Int('dense_units1', 32, 256, step=32), activation='relu', kernel_regularizer=regularizers.l2(hp.Float('l2_strength', 1e-5, 1e-2, sampling='log'))))
    model.add(layers.Dense(hp.Int('dense_units2', 32, 256, step=32), activation='relu', kernel_regularizer=regularizers.l2(hp.Float('l2_strength', 1e-5, 1e-2, sampling='log'))))
    model.add(layers.Dense(hp.Int('dense_units3', 32, 256, step=32), activation='relu', kernel_regularizer=regularizers.l2(hp.Float('l2_strength', 1e-5, 1e-2, sampling='log'))))
    model.add(layers.Dense(3, activation='softmax'))

    loss = 'sparse_categorical_crossentropy'
    optim = keras.optimizers.Adam(learning_rate=hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])) #from 0.001
    metrics = ["accuracy"]

    model.compile(loss=loss, optimizer=optim, metrics=metrics)



    return model

In [ ]:
import keras_tuner as kt

tuner = kt.BayesianOptimization(build_model, 
                                objective='val_accuracy',
                                max_trials=15,
                                executions_per_trial=1, 
                                beta=2.6)

In [ ]:
tuner.search(training_padded, training_labels, epochs=10, validation_data=(validation_padded, validation_labels), class_weight=class_weights, batch_size=32, verbose=2)

Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
64                |64                |embedding_dim
128               |128               |lstm_units
160               |160               |dense_units1
6.8245e-05        |6.8245e-05        |l2_strength
32                |32                |dense_units2
192               |192               |dense_units3
0.001             |0.001             |learning_rate

Epoch 1/10

In [ ]:
best = tuner.get_best_models(num_models=1)[0]

loss, accuracy = best.evaluate(validation_padded, validation_labels, verbose=2)

print(f"Validation Loss: {loss}, Validation Accuracy: {accuracy}")
best.summary()