# Data Preparation

In [42]:
import pandas
import matplotlib.pyplot as plt
from collections import Counter
import string
import numpy as np

from tensorflow.keras import layers
from tensorflow.keras import losses

wf = pandas.read_csv("./EMPOLITICON.csv")
wf

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,16/07/2021,Vladimir Putin,Meeting of APEC Economic Leaders,"Madam Chair,\n\nColleagues,\n\nFirst of all, ...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,OPTIMISM,DEVELOPMENT
1,Russia,2021-09-05 00:00:00,Vladimir Putin,Victory Parade on Red Square,"Citizens of Russia,\n\nDear veterans,\n\nComra...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,JOY,NATIONALISM
2,Russia,2021-08-04 00:00:00,Vladimir Putin,Meeting on the results of implementing Preside...,"Good afternoon, colleagues.\n\nLet’s start.\n\...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,DEVELOPMENT
3,Russia,21-11-2020,Vladimir Putin,G20 Summit,"Colleagues,\n\nThe scope of problems humanity ...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,DEVELOPMENT
4,Russia,20-11-2020,Vladimir Putin,Address to participants in Nuremberg Lessons f...,"Colleagues, friends,\n\nFirst of all, I would ...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,UPSET,EXTREMISM
...,...,...,...,...,...,...,...,...,...,...
2005,USA,05/02/2013,Barack Obama,\nRemarks by the President,"Good afternoon, everybody. \n\nI wanted to sa...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,NEUTRAL,DEVELOPMENT
2006,USA,04/02/2013,Barack Obama,\nRemarks by the President on Preventing Gun V...,"Hello, everybody. Please have a seat. Have a...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,NEUTRAL,OTHERS
2007,USA,02/02/2013,Barack Obama,\nWeekly Address: A Balanced Approach to Growi...,"Hi, everybody. \n\nIn the coming weeks, we fa...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,OPTIMISM,DEVELOPMENT
2008,USA,28/01/2013,Barack Obama,\nRemarks by the President Before Meeting with...,"Well, Vice President Biden and I just want to...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,OPTIMISM,OTHERS
2009,USA,21/01/2013,Barack Obama,\nInaugural Address by President Barack Obama,"Vice President Biden, Mr. Chief Justice,\nmemb...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,JOY,OTHERS

In [43]:
# shuffing the data
wf = wf.sample(frac=1).reset_index(drop=True)
wf

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,2003-02-02 00:00:00,Vladimir Putin,Speech at the Ceremony Marking the 60th Annive...,Dear friends!\n\nDear veterans!\n\nI congratul...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,JOY,NATIONALISM
1,USA,2021-08-23 00:00:00,Joe Biden,Remarks by President Biden on the COVID-⁠19 Re...,"THE PRESIDENT: Good afternoon. Today, we hav...",President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,OPTIMISM,DEVELOPMENT
2,USA,2021-03-23 00:00:00,Joe Biden,Remarks by President Biden on the Anniversary ...,"THE PRESIDENT: Good afternoon, almost getting...",President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,OPTIMISM,DEVELOPMENT
3,Russia,2006-07-04 00:00:00,Vladimir Putin,Opening Remarks at Meeting of the Council for ...,"Good afternoon, dear colleagues.\n\nThis is th...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,DEVELOPMENT
4,USA,2021-02-25 00:00:00,Joe Biden,Remarks by President Biden at the National Gov...,THE PRESIDENT: Thank you very much. Thank yo...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,OPTIMISM,DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
2005,USA,2017-12-09 00:00:00,Donald Trump,Remarks by President Trump at the Opening of t...,THE PRESIDENT: Thank you very much. Thank yo...,President,Donald Trump,https://trumpwhitehouse.archives.gov/briefings...,JOY,OTHERS
2006,Russia,20-11-2008,Dmitry Medvedev,Speech at the 10th United Russia party congress,Good day dear colleagues!\n\nI am happy to wel...,President,Dmitry Medvedev,http://en.kremlin.ru/events/president/transcri...,NEUTRAL,OTHERS
2007,USA,24/11/2016,Barack Obama,\nWEEKLY ADDRESS: Coming Together On Thanksgiving,"Hi, everybody. On behalf of the Obama family...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,JOY,OTHERS
2008,Russia,31-03-2016,Vladimir Putin,Security Council Meeting,"Good afternoon, colleagues,\n\nToday we will d...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,UPSET,INTERNATIONAL AFFAIRS
2009,USA,07/08/2014,Barack Obama,\nStatement by the President,Good evening. Today I authorized two operatio...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,NEUTRAL,INTERNATIONAL AFFAIRS

In [44]:
def count_unique_word(wf):
    count = Counter()
    for word in wf['Emotion']:
        count[word] += 1
    return count

counter = count_unique_word(wf)

In [45]:
print(counter.most_common())

[('NEUTRAL', 589), ('OPTIMISM', 583), ('JOY', 525), ('UPSET', 313)]

Setting labels for a multi-classification problem

In [46]:
#labeling the emotion column such that they are classified as neutral, positive, or negative
for i in range(len(wf)):
    if wf['Emotion'][i] == counter.most_common()[0][0]:
        wf['Emotion'][i] = 0
    elif wf['Emotion'][i] == counter.most_common()[1][0]:
        wf['Emotion'][i] = 1
    elif wf['Emotion'][i] == counter.most_common()[2][0]:
        wf['Emotion'][i] = 1
    elif wf['Emotion'][i] == counter.most_common()[3][0]:
        wf['Emotion'][i] = 2

#these labels will be used to train the model

/tmp/ipykernel_69110/1175571102.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Emotion'][i] = 1
/tmp/ipykernel_69110/1175571102.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Emotion'][i] = 1
/tmp/ipykernel_69110/1175571102.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Emotion'][i] = 0
/tmp/ipykernel_69110/1175571102.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Emotion'][i] = 2

In [47]:
wf

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,Russia,2003-02-02 00:00:00,Vladimir Putin,Speech at the Ceremony Marking the 60th Annive...,Dear friends!\n\nDear veterans!\n\nI congratul...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,1,NATIONALISM
1,USA,2021-08-23 00:00:00,Joe Biden,Remarks by President Biden on the COVID-⁠19 Re...,"THE PRESIDENT: Good afternoon. Today, we hav...",President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,1,DEVELOPMENT
2,USA,2021-03-23 00:00:00,Joe Biden,Remarks by President Biden on the Anniversary ...,"THE PRESIDENT: Good afternoon, almost getting...",President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,1,DEVELOPMENT
3,Russia,2006-07-04 00:00:00,Vladimir Putin,Opening Remarks at Meeting of the Council for ...,"Good afternoon, dear colleagues.\n\nThis is th...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,0,DEVELOPMENT
4,USA,2021-02-25 00:00:00,Joe Biden,Remarks by President Biden at the National Gov...,THE PRESIDENT: Thank you very much. Thank yo...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,1,DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
2005,USA,2017-12-09 00:00:00,Donald Trump,Remarks by President Trump at the Opening of t...,THE PRESIDENT: Thank you very much. Thank yo...,President,Donald Trump,https://trumpwhitehouse.archives.gov/briefings...,1,OTHERS
2006,Russia,20-11-2008,Dmitry Medvedev,Speech at the 10th United Russia party congress,Good day dear colleagues!\n\nI am happy to wel...,President,Dmitry Medvedev,http://en.kremlin.ru/events/president/transcri...,0,OTHERS
2007,USA,24/11/2016,Barack Obama,\nWEEKLY ADDRESS: Coming Together On Thanksgiving,"Hi, everybody. On behalf of the Obama family...",President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,OTHERS
2008,Russia,31-03-2016,Vladimir Putin,Security Council Meeting,"Good afternoon, colleagues,\n\nToday we will d...",President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,2,INTERNATIONAL AFFAIRS
2009,USA,07/08/2014,Barack Obama,\nStatement by the President,Good evening. Today I authorized two operatio...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,0,INTERNATIONAL AFFAIRS

In [48]:
# wf = wf.head(739)

In [49]:
wf.iloc[76]['Text_of_Speech']

' Hi, everybody.  This week, I visited a company in Raleigh, North Carolina that helps make electric motors that save businesses money on energy costs and cut harmful carbon pollution. \n\nAnd I stopped by N.C. State University, where engineers are set to develop the new technology that will make those motors even better.\n\nIt’s part of my push not only to make America home to more high-tech manufacturing – but to make America more attractive for the good jobs that a growing middle class requires. \n\nAnd increasingly, we are.  Thanks in part to our all-of-the-above strategy for American energy, for the first time in nearly two decades, we produce more oil here at home than we buy from the rest of the world.  We generate more renewable energy than ever, and more natural gas than anybody.  Health care costs are growing at their slowest rate in 50 years – due in part to the Affordable Care Act.  And since I took office, we’ve cut our deficits by more than half.\n\nSo we are primed to bring back more of the good jobs claimed by the recession, and lost to overseas competition in recent decades.  But that requires a year of action.  And I want to work with Congress this year on proven ways to create jobs, like building infrastructure and fixing our broken immigration system.\n\nWhere Congress isn’t acting, I’ll act on my own to put opportunity within reach for anyone who’s willing to work for it. That’s what I did in Raleigh by launching America’s second “manufacturing innovation institute.”  It’s a partnership between companies, colleges, and the federal government focused on making sure American businesses and American workers win the race for high-tech manufacturing and the jobs that come with it – jobs that can help people and communities willing to work hard punch their ticket into the middle class. \n\nI firmly believe that this can be a breakthrough year for America.  But to make that happen, we’re gonna have to act – to create good jobs that pay good wages, and to offer more Americans a fair shot to get ahead.  That’s what I’m focused on every day that I have the privilege of serving as your president. That’s what I’m going to be focused on every single day of this year.\n\nThanks, and have a great weekend.'

In [50]:
## one thing we can do is to use the model from the presidential classifier and then, if a given speech is classified
## as angry or some other negative mood, and it includes the word "US, NATO", or something related to the west, we classify it as adversarial

In [51]:
#removing the punctuation

## Yet to apply this to the data

def remove_punctuation(text):
    translator = str.maketrans("", "", string.punctuation)
    return text.translate(translator)

In [52]:
#removing the stop words (commonly used words that do not add much meaning to a sentence)

## Yet to actually apply this function to the data

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop = set(stopwords.words("english"))

def remove_stopwords(text):
    #removes stop words
    filtered_words = [word.lower() for word in text.split() if word.lower() not in stop]
    return " ".join(filtered_words)

[nltk_data] Downloading package stopwords to /home/yash/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
#cleaning up the speeches so that common stopwords and puntuation are removed
for i in range(len(wf['Text_of_Speech'])):
    wf['Text_of_Speech'][i] = remove_punctuation(wf['Text_of_Speech'][i])
    wf['Text_of_Speech'][i] = remove_stopwords(wf['Text_of_Speech'][i])

/tmp/ipykernel_69110/2134825500.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Text_of_Speech'][i] = remove_punctuation(wf['Text_of_Speech'][i])
/tmp/ipykernel_69110/2134825500.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wf['Text_of_Speech'][i] = remove_stopwords(wf['Text_of_Speech'][i])

In [ ]:
#drop rows without string in speech
for i in range(len(wf) - 1, -1, -1):
        if not (isinstance(wf.iloc[i]['Text_of_Speech'], str)):
                wf = wf.drop(i)

In [ ]:
#counting the number of unique words in each speech


def count_unique_word(wf_training):
    count = Counter()
    for i in range(len(wf_training)):
        for word in wf_training.iloc[i]['Text_of_Speech'].split():
            count[word] += 1
    return count

counter = count_unique_word(wf)

In [ ]:
counter

Counter({'people': 9977,
         '—': 8222,
         'new': 6587,
         'world': 6530,
         'work': 6325,
         'us': 6261,
         'china': 6246,
         'countries': 6156,
         'development': 6030,
         'one': 5367,
         'also': 5297,
         'country': 5190,
         'cooperation': 5139,
         'today': 4997,
         'need': 4856,
         'make': 4751,
         'thank': 4400,
         'years': 4319,
         'like': 4236,
         'must': 4210,
         'going': 4136,
         'want': 4067,
         'know': 4061,
         'would': 3998,
         'it’s': 3995,
         'time': 3944,
         'international': 3876,
         'economic': 3761,
         'many': 3709,
         'applause': 3698,
         'first': 3525,
         'we’re': 3520,
         '–': 3500,
         'year': 3467,
         'security': 3461,
         'united': 3394,
         'economy': 3278,
         'states': 3250,
         'that’s': 3248,
         'every': 3222,
         'great': 3150,
         'important': 3121,
         'get': 3113,
         'together': 3081,
         'american': 3075,
         'good': 2925,
         'government': 2885,
         'way': 2808,
         'much': 2796,
         'america': 2769,
         'support': 2767,
         'state': 2744,
         'right': 2705,
         'global': 2697,
         'take': 2653,
         'help': 2564,
         'well': 2558,
         'president': 2520,
         'think': 2490,
         'two': 2466,
         'future': 2365,
         'system': 2354,
         'national': 2342,
         'made': 2333,
         'even': 2319,
         'russia': 2247,
         'law': 2237,
         'last': 2180,
         'continue': 2167,
         'say': 2143,
         'we’ve': 2136,
         'working': 2110,
         'back': 2108,
         'growth': 2096,
         'chinese': 2063,
         'see': 2031,
         'peace': 2019,
         'americans': 2013,
         'trade': 1987,
         'said': 1972,
         'jobs': 1960,
         'better': 1931,
         'come': 1918,
         'part': 1885,
         'still': 1869,
         'day': 1800,
         'families': 1777,
         'including': 1768,
         'community': 1750,
         'got': 1749,
         'business': 1730,
         'nation': 1716,
         'efforts': 1705,
         'build': 1701,
         'sure': 1693,
         'already': 1687,
         'i’m': 1677,
         'russian': 1674,
         'keep': 1650,
         'around': 1650,
         'course': 1639,
         'progress': 1631,
         'let': 1629,
         'lives': 1628,
         'common': 1627,
         'done': 1609,
         'health': 1595,
         'could': 1594,
         'long': 1581,
         'life': 1581,
         'never': 1568,
         'relations': 1521,
         'across': 1519,
         'political': 1517,
         'put': 1516,
         'interests': 1513,
         'go': 1507,
         'place': 1503,
         'million': 1487,
         'history': 1486,
         'war': 1486,
         'military': 1485,
         'past': 1484,
         'may': 1482,
         'public': 1473,
         'always': 1466,
         'regional': 1466,
         'nations': 1463,
         'social': 1457,
         'making': 1447,
         'believe': 1432,
         'number': 1422,
         'change': 1413,
         'friends': 1409,
         'give': 1402,
         'don’t': 1390,
         'issues': 1373,
         'problems': 1373,
         'region': 1364,
         'things': 1364,
         'investment': 1363,
         'job': 1351,
         'open': 1346,
         'ago': 1339,
         'federal': 1334,
         'care': 1331,
         'hope': 1327,
         'lot': 1325,
         'forward': 1303,
         'situation': 1303,
         'set': 1301,
         'energy': 1299,
         'look': 1298,
         'able': 1284,
         'end': 1281,
         'leaders': 1278,
         'home': 1277,
         'use': 1274,
         'since': 1271,
         'next': 1270,
         'percent': 1266,
         'education': 1255,
         'children': 1255,
         'citizens': 1251,
         'plan': 1244,
         'chinas': 1237,
         'best': 1236,
         'rights': 1232,
         'means': 1227,
         'they’re': 1226,
         'everybody': 1204,
         'developing': 1204,
         'power': 1196,
         'building': 1195,
         'ensure': 1192,
         'women': 1179,
         'major': 1178,
         'create': 1176,
         'policy': 1169,
         'another': 1168,
         'ever': 1168,
         'clear': 1167,
         'foreign': 1165,
         'without': 1163,
         'possible': 1162,
         'congress': 1158,
         'strong': 1156,
         'meeting': 1153,
         'reform': 1144,
         'second': 1134,
         'society': 1133,
         'members': 1129,
         'order': 1129,
         'businesses': 1128,
         'something': 1125,
         'hard': 1123,
         'areas': 1115,
         'different': 1115,
         'act': 1112,
         'opportunity': 1110,
         'free': 1110,
         'financial': 1103,
         'issue': 1102,
         'young': 1100,
         'human': 1098,
         'africa': 1094,
         'three': 1083,
         'laughter': 1082,
         'times': 1081,
         'service': 1079,
         'forces': 1074,
         'companies': 1065,
         'market': 1059,
         'big': 1054,
         'local': 1049,
         'protect': 1046,
         'billion': 1045,
         'far': 1041,
         'workers': 1028,
         'family': 1027,
         'challenges': 1025,
         'regions': 1025,
         'others': 1015,
         'whole': 1013,
         'measures': 1008,
         'infrastructure': 1002,
         'nuclear': 995,
         'colleagues': 993,
         'road': 993,
         'level': 992,
         'respect': 988,
         'un': 988,
         'general': 986,
         'pay': 986,
         'provide': 985,
         'mutual': 983,
         'shared': 979,
         'i’ve': 976,
         'become': 967,
         'council': 958,
         'role': 955,
         'everyone': 955,
         'cannot': 947,
         'thing': 945,
         'really': 945,
         'fight': 937,
         'fact': 936,
         'special': 932,
         'you’re': 932,
         'stand': 920,
         'needs': 919,
         'bring': 918,
         'everything': 911,
         'resources': 907,
         'process': 906,
         'god': 904,
         'promote': 901,
         'increase': 898,
         'taking': 896,
         'greater': 895,
         'stability': 893,
         'crisis': 892,
         'taken': 887,
         'action': 885,
         'real': 884,
         'share': 884,
         'high': 880,
         'effective': 876,
         'necessary': 875,
         'communities': 875,
         'deal': 873,
         'seen': 872,
         'tax': 864,
         'peoples': 862,
         'climate': 855,
         'services': 847,
         'force': 847,
         'among': 840,
         'full': 839,
         'opportunities': 839,
         'days': 836,
         'live': 833,
         'partners': 832,
         'ready': 822,
         'improve': 817,
         'there’s': 812,
         'start': 811,
         'achieve': 809,
         'justice': 808,
         'prosperity': 804,
         'point': 803,
         'europe': 800,
         'sector': 797,
         'parties': 787,
         'asia': 785,
         'house': 780,
         'money': 780,
         'months': 778,
         'folks': 778,
         'meet': 776,
         'millions': 775,
         'potential': 774,
         'strengthen': 764,
         'summit': 760,
         'step': 758,
         'responsibility': 756,
         'projects': 755,
         'mr': 754,
         'five': 754,
         'partnership': 753,
         'coming': 750,
         'attention': 750,
         'freedom': 749,
         'face': 748,
         'technology': 748,
         'african': 740,
         'address': 738,
         'example': 737,
         'strategic': 736,
         'within': 732,
         'problem': 732,
         'dear': 731,
         'ahead': 730,
         'middle': 728,
         'thanks': 728,
         'innovation': 725,
         'getting': 724,
         'success': 722,
         'yet': 720,
         'principles': 718,
         'men': 715,
         'conditions': 712,
         'took': 705,
         'especially': 704,
         'remember': 703,
         'east': 702,
         'committed': 701,
         'school': 701,
         'approach': 700,
         'proud': 699,
         'entire': 699,
         'week': 698,
         'key': 697,
         'joint': 695,
         'love': 693,
         'area': 692,
         'understand': 691,
         'single': 689,
         'secretary': 684,
         'fully': 684,
         'democracy': 682,
         'third': 681,
         'find': 679,
         'afghanistan': 675,
         'modern': 674,
         'true': 674,
         'information': 671,
         'office': 670,
         'growing': 667,
         'terrorism': 665,
         'agreement': 664,
         'commitment': 662,
         'develop': 662,
         'less': 657,
         'matter': 653,
         'minister': 652,
         'schools': 651,
         'small': 649,
         'decades': 648,
         'we’ll': 647,
         'steps': 645,
         'tell': 643,
         'rules': 643,
         'values': 642,
         'given': 641,
         'civil': 641,
         'moment': 640,
         'enforcement': 638,
         'often': 636,
         'budget': 636,
         'task': 635,
         'initiative': 635,
         'european': 634,
         'chance': 633,
         'came': 630,
         'difficult': 629,
         'actions': 628,
         'kind': 628,
         'union': 628,
         'safe': 626,
         'administration': 626,
         'control': 622,
         'quality': 622,
         'friendship': 621,
         'century': 618,
         'results': 617,
         'honor': 616,
         'incredible': 616,
         'fair': 614,
         'peaceful': 613,
         'decisions': 613,
         'can’t': 613,
         'benefits': 613,
         'south': 612,
         'close': 611,
         'spirit': 608,
         'environment': 608,
         'lead': 606,
         'leadership': 605,
         'dialogue': 603,
         'enough': 601,
         'path': 601,
         'effort': 600,
         'rate': 600,
         'wish': 597,
         'whether': 596,
         'used': 596,
         'poverty': 594,
         'mean': 592,
         'finally': 592,
         'four': 591,
         'move': 587,
         'turn': 587,
         'stronger': 587,
         'sustainable': 586,
         'worked': 586,
         'focus': 583,
         'based': 583,
         'laws': 582,
         'access': 581,
         'police': 581,
         'virus': 580,
         'changes': 580,
         'veterans': 580,
         'covid19': 580,
         'agenda': 579,
         'ways': 578,
         'main': 577,
         'call': 577,
         'thousands': 576,
         'little': 576,
         'experience': 575,
         'threat': 575,
         'along': 575,
         'bless': 570,
         'welcome': 568,
         'words': 568,
         'makes': 567,
         'priority': 566,
         'goal': 564,
         'capacity': 559,
         'remain': 559,
         'nearly': 559,
         'half': 557,
         'created': 555,
         'violence': 554,
         'ask': 554,
         'benefit': 551,
         'play': 550,
         'serious': 549,
         'lost': 549,
         'sense': 545,
         'stop': 545,
         'higher': 545,
         'advance': 544,
         'helping': 543,
         'stay': 541,
         'exchanges': 540,
         'prime': 540,
         'uk': 540,
         'living': 539,
         'particular': 538,
         'science': 536,
         'simply': 536,
         'talk': 536,
         'current': 535,
         'trust': 534,
         'legal': 534,
         'threats': 532,
         'ones': 531,
         'basis': 530,
         'line': 527,
         'various': 525,
         'recent': 524,
         'authorities': 524,
         'weeks': 523,
         'uphold': 523,
         'serve': 521,
         'strength': 520,
         'nothing': 520,
         'allow': 518,
         'terrorist': 518,
         'governance': 518,
         'longterm': 517,
         'students': 517,
         'you’ve': 517,
         'early': 516,
         'fighting': 515,
         'join': 515,
         'comprehensive': 513,
         'reason': 512,
         'party': 512,
         'almost': 511,
         'groups': 511,
         'agencies': 510,
         'behind': 509,
         'responsible': 508,
         'helped': 507,
         'strategy': 506,
         'grow': 506,
         'winwin': 506,
         'gentlemen': 503,
         'away': 502,
         'plans': 502,
         'old': 502,
         'xi': 502,
         'discuss': 501,
         'assistance': 499,
         'generation': 498,
         'training': 496,
         'britain': 496,
         'bill': 495,
         'let’s': 495,
         'pursue': 494,
         'remains': 493,
         'ladies': 493,
         'industrial': 493,
         'actually': 493,
         'border': 493,
         'standards': 492,
         'ministry': 492,
         'safety': 491,
         'industry': 490,
         'creating': 490,
         'thats': 490,
         'institutions': 487,
         'relationship': 487,
         'called': 485,
         'month': 484,
         'top': 484,
         'large': 483,
         'basic': 482,
         'positive': 481,
         'vision': 480,
         'forum': 480,
         'built': 478,
         'russia’s': 477,
         'visit': 476,
         'city': 476,
         'hold': 475,
         'cases': 475,
         'culture': 474,
         'asean': 474,
         'speak': 473,
         'america’s': 473,
         'central': 473,
         'armed': 472,
         'country’s': 471,
         'cut': 471,
         'prevent': 471,
         'private': 470,
         'research': 469,
         'enhance': 467,
         'victory': 467,
         'belt': 467,
         'looking': 466,
         'several': 466,
         'following': 464,
         'eu': 464,
         'north': 463,
         'developed': 462,
         'production': 462,
         'met': 462,
         'resolve': 461,
         'challenge': 460,
         'space': 459,
         'significant': 457,
         'case': 457,
         'protection': 456,
         'active': 456,
         'largest': 455,
         'beyond': 454,
         'follow': 454,
         'held': 453,
         'ideas': 453,
         'class': 452,
         'goals': 451,
         'response': 451,
         'faith': 451,
         'terrorists': 450,
         'signed': 450,
         'anniversary': 449,
         'pandemic': 449,
         'ground': 447,
         'happen': 447,
         'housing': 447,
         'position': 445,
         'truly': 445,
         'expand': 445,
         'involved': 445,
         'passed': 444,
         'save': 443,
         'markets': 443,
         'soon': 443,
         'economies': 442,
         'asian': 442,
         'raise': 442,
         'deliver': 442,
         'feel': 442,
         'leading': 440,
         'least': 440,
         'sides': 439,
         'result': 438,
         'land': 435,
         'recovery': 434,
         'weapons': 433,
         'leave': 433,
         'interest': 433,
         'saying': 433,
         'seek': 430,
         'legislation': 430,
         'certain': 430,
         'medical': 429,
         'foundation': 428,
         'fundamental': 428,
         'events': 427,
         'decision': 427,
         'coordination': 426,
         'reduce': 426,
         'troops': 425,
         'vital': 424,
         'equal': 424,
         'question': 424,
         'member': 423,
         'begin': 422,
         'brought': 422,
         'left': 421,
         'however': 420,
         'group': 418,
         'present': 417,
         'mission': 416,
         'cities': 416,
         'choice': 416,
         'tasks': 416,
         'historic': 416,
         'isil': 416,
         'syria': 415,
         'child': 415,
         'what’s': 415,
         'jointly': 414,
         'affairs': 414,
         'comes': 412,
         'rest': 412,
         'idea': 411,
         'might': 411,
         'six': 411,
         'trying': 411,
         'courage': 410,
         'domestic': 410,
         'hear': 409,
         'policies': 408,
         'dollars': 408,
         'systems': 408,
         'officers': 407,
         'confidence': 406,
         'representatives': 405,
         'needed': 405,
         'insurance': 405,
         'relevant': 404,
         'carry': 404,
         'iraq': 404,
         'contribution': 404,
         'overall': 403,
         'extraordinary': 403,
         'reach': 403,
         'secure': 403,
         'afternoon': 402,
         'critical': 402,
         '10': 402,
         'agree': 402,
         'cost': 402,
         'personnel': 401,
         'period': 401,
         'actively': 400,
         'show': 400,
         'talking': 400,
         'man': 399,
         'they’ve': 399,
         'please': 397,
         'happened': 397,
         'importance': 396,
         'cultural': 395,
         'therefore': 395,
         'democratic': 394,
         'terms': 394,
         'rather': 394,
         'dignity': 393,
         'technologies': 393,
         'heard': 393,
         'heart': 391,
         'federation': 391,
         'goods': 389,
         'manufacturing': 389,
         'towards': 388,
         'diplomacy': 387,
         'iran': 386,
         'sometimes': 385,
         'organizations': 385,
         'vote': 384,
         'drug': 384,
         'kids': 384,
         'equipment': 384,
         'instead': 383,
         'demand': 381,
         'risk': 381,
         'yesterday': 381,
         'doesn’t': 379,
         'levels': 379,
         'criminal': 379,
         'affordable': 379,
         'diplomatic': 379,
         'green': 378,
         'alone': 377,
         'framework': 376,
         'huge': 376,
         'executive': 375,
         'particularly': 375,
         'longer': 375,
         'heads': 375,
         'supply': 374,
         'fellow': 374,
         'implement': 373,
         'speaker': 373,
         'republicans': 373,
         'biggest': 373,
         'recently': 373,
         '100': 373,
         'view': 372,
         'crime': 372,
         'allies': 371,
         '50': 371,
         'ensuring': 371,
         'side': 370,
         'stage': 370,
         'increasing': 370,
         'stable': 369,
         'beautiful': 369,
         'white': 369,
         '20': 368,
         'weve': 367,
         'team': 367,
         'agreed': 365,
         'invest': 365,
         'goes': 365,
         'saw': 364,
         'investments': 364,
         'british': 364,
         'promoting': 363,
         'rule': 363,
         'absolutely': 363,
         'understanding': 362,
         'people’s': 362,
         'beginning': 362,
         'paid': 362,
         'greatest': 362,
         'story': 362,
         'achieved': 361,
         'throughout': 361,
         'places': 360,
         'hand': 359,
         'activities': 359,
         'improving': 359,
         'republic': 358,
         'encourage': 358,
         'didn’t': 358,
         'jinping': 358,
         'spread': 357,
         'additional': 356,
         'toward': 356,
         'told': 356,
         'went': 355,
         'stress': 354,
         'works': 354,
         'conflict': 353,
         'capital': 353,
         'governments': 353,
         'defence': 353,
         'started': 352,
         'try': 351,
         'maintain': 351,
         'department': 351,
         'integration': 351,
         'implementation': 350,
         'fourth': 349,
         'exchange': 349,
         'effectively': 349,
         'costs': 349,
         'internet': 349,
         'sea': 348,
         'draw': 348,
         'directly': 348,
         'though': 348,
         'morning': 347,
         'impact': 346,
         'asiapacific': 346,
         'independent': 346,
         'thought': 346,
         'successful': 345,
         'opening': 345,
         'humanitarian': 344,
         'pass': 344,

In [ ]:
num_unique_words = len(counter)

In [ ]:
print(len(wf))

2010

In [ ]:
#80% training 20% testing split
wf_training = wf[:int(len(wf) * 0.8)]
wf_testing = wf[int(len(wf) * 0.8):]

In [ ]:
wf_testing.reset_index(inplace=True)
wf_testing.drop('index', axis=1, inplace=True)
wf_testing

/tmp/ipykernel_69110/3894747268.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wf_testing.drop('index', axis=1, inplace=True)

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,United Kingdom,11 October 2010,David Cameron,PM press conference,read transcript good morning start press confe...,Prime Minister,David Cameron,https://www.gov.uk/government/speeches/pm-pres...,2,OTHERS
1,USA,14/11/2014,Barack Obama,\nRemarks by President Obama After Civil Socie...,well i’ve opportunity speak excellent crosssec...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,OTHERS
2,USA,19/10/2013,Barack Obama,\nWeekly Address: Working Together on Behalf o...,hi everybody week democrats responsible republ...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,0,DEVELOPMENT
3,USA,2021-06-26 00:00:00,Joe Biden,"Statement by President Joseph R. Biden, Jr. on...",today anniversary united nations convention to...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,0,OTHERS
4,Russia,2006-03-02 00:00:00,Vladimir Putin,Excerpts from Speech at the Session of the Col...,prosecutor general’s office many areas work on...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,2,OTHERS
...,...,...,...,...,...,...,...,...,...,...
397,USA,2021-10-26 00:00:00,Joe Biden,Remarks by President Biden at the Annual U.S.-...,president well thank sultan bringing us togeth...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/speec...,1,INTERNATIONAL AFFAIRS
398,USA,2020-01-08 00:00:00,Donald Trump,Remarks by President Trump on Iran,president long president united states iran ne...,President,Donald Trump,https://trumpwhitehouse.archives.gov/briefings...,2,EXTREMISM
399,USA,4/1/2017,Barack Obama,\nRemarks by the President at Armed Forces Ful...,thank much thank applause thank please seated ...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,NATIONALISM
400,USA,2021-04-01 00:00:00,Joe Biden,Letter to the Speaker of the House and the Pre...,dear madam speaker dear madam president sectio...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,2,INTERNATIONAL AFFAIRS
401,Russia,26-10-2020,Vladimir Putin,Statement by Vladimir Putin on additional step...,russian federation continues believe inf treat...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,2,INTERNATIONAL AFFAIRS

In [ ]:
wf_training.reset_index(inplace=True)
wf_training.drop('index', axis=1, inplace=True)
wf_training

/tmp/ipykernel_69110/1694703126.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wf_training.drop('index', axis=1, inplace=True)

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,USA,17/11/2015,Barack Obama,Remarks by President Obama After Touring the B...,good afternoon everybody wonderful back philip...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,DEVELOPMENT
1,China,2014-01-22 00:00:00,H.E. Wang Yi,Wang Yi:Seek Common Ground While Shelving Diff...,secretary general ban kimoon dear colleagues t...,State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,0,INTERNATIONAL AFFAIRS
2,USA,2021-02-10 00:00:00,Joe Biden,A Letter to the Speaker of the House of Repres...,tter speaker house representatives president s...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,1,OTHERS
3,USA,2021-05-14 00:00:00,Joe Biden,Statement by President Joe Biden on House Pass...,applaud chairman nadler chairman scott ranking...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,0,DEVELOPMENT
4,United Kingdom,2 November 2020,Boris Johnson,PM Commons statement on coronavirus: 2 November,mr speaker permission make statement measures ...,Prime Minister,Boris Johnson,https://www.gov.uk/government/speeches/pm-comm...,2,DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
1603,USA,2021-10-08 00:00:00,Joe Biden,Statement of President Joe Biden on Signing HA...,today pleased sign havana act law ensure utmos...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,1,OTHERS
1604,USA,13/11/2015,Barack Obama,\nRemarks by the President in Meeting on the T...,many know weekend leaving trip g20 i’ll taking...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,INTERNATIONAL AFFAIRS
1605,Russia,2010-08-08 00:00:00,Dmitry Medvedev,Speech at visit to Russian military base in Gu...,today special day country’s history history ab...,President,Dmitry Medvedev,http://en.kremlin.ru/events/president/transcri...,1,OTHERS
1606,Russia,21-01-2010,Dmitry Medvedev,Speech at Year of the Teacher Opening Ceremony,good afternoon colleagues pleased speak hall s...,President,Dmitry Medvedev,http://en.kremlin.ru/events/president/transcri...,1,OTHERS
1607,Russia,30-12-2016,Vladimir Putin,Statement by the President of Russia,regard recent unfriendly steps taken outgoing ...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,2,INTERNATIONAL AFFAIRS

In [ ]:
wf_training

,Country,Date,Speaker,Headline,Text_of_Speech,Designation,Running President/PM,Speech Link,Emotion,Context
0,USA,17/11/2015,Barack Obama,Remarks by President Obama After Touring the B...,good afternoon everybody wonderful back philip...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,DEVELOPMENT
1,China,2014-01-22 00:00:00,H.E. Wang Yi,Wang Yi:Seek Common Ground While Shelving Diff...,secretary general ban kimoon dear colleagues t...,State Councilor and Foreign Minister of the Pe...,Xi Jinping,https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...,0,INTERNATIONAL AFFAIRS
2,USA,2021-02-10 00:00:00,Joe Biden,A Letter to the Speaker of the House of Repres...,tter speaker house representatives president s...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,1,OTHERS
3,USA,2021-05-14 00:00:00,Joe Biden,Statement by President Joe Biden on House Pass...,applaud chairman nadler chairman scott ranking...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,0,DEVELOPMENT
4,United Kingdom,2 November 2020,Boris Johnson,PM Commons statement on coronavirus: 2 November,mr speaker permission make statement measures ...,Prime Minister,Boris Johnson,https://www.gov.uk/government/speeches/pm-comm...,2,DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
1603,USA,2021-10-08 00:00:00,Joe Biden,Statement of President Joe Biden on Signing HA...,today pleased sign havana act law ensure utmos...,President,Joe Biden,https://www.whitehouse.gov/briefing-room/state...,1,OTHERS
1604,USA,13/11/2015,Barack Obama,\nRemarks by the President in Meeting on the T...,many know weekend leaving trip g20 i’ll taking...,President,Barack Obama,https://obamawhitehouse.archives.gov/the-press...,1,INTERNATIONAL AFFAIRS
1605,Russia,2010-08-08 00:00:00,Dmitry Medvedev,Speech at visit to Russian military base in Gu...,today special day country’s history history ab...,President,Dmitry Medvedev,http://en.kremlin.ru/events/president/transcri...,1,OTHERS
1606,Russia,21-01-2010,Dmitry Medvedev,Speech at Year of the Teacher Opening Ceremony,good afternoon colleagues pleased speak hall s...,President,Dmitry Medvedev,http://en.kremlin.ru/events/president/transcri...,1,OTHERS
1607,Russia,30-12-2016,Vladimir Putin,Statement by the President of Russia,regard recent unfriendly steps taken outgoing ...,President,Vladimir Putin,http://en.kremlin.ru/events/president/transcri...,2,INTERNATIONAL AFFAIRS

In [ ]:
training_sentences = wf_training.Text_of_Speech.to_numpy()
#training labels
training_labels = wf_training.Emotion.to_numpy()

validation_sentences = wf_testing.Text_of_Speech.to_numpy()
#training labels
validation_labels = wf_testing.Emotion.to_numpy()

In [ ]:
training_sentences.shape, validation_sentences.shape

((1608,), (402,))

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=num_unique_words)
tokenizer.fit_on_texts(training_sentences)

In [ ]:
word_index = tokenizer.word_index

In [ ]:
training_sequences = tokenizer.texts_to_sequences(training_sentences)
validation_sequences = tokenizer.texts_to_sequences(validation_sentences)

In [ ]:
#padding sequences to have the same length
from tensorflow.keras.preprocessing.sequence import pad_sequences

#max number of words per sequence
max_length = 500

training_padded = pad_sequences(training_sequences, maxlen=max_length, padding="post", truncating="post")
validation_padded = pad_sequences(validation_sequences, maxlen=max_length, padding="post", truncating="post")
training_padded.shape, validation_padded.shape

((1608, 500), (402, 500))

In [ ]:
print(num_unique_words)

38938

In [ ]:
#LSTM Model
import tensorflow.keras as keras


#embedding layer converts the words into vectors of fixed size
#dropout rate drops out a certain percentage of input data so that the
#model learns more robust ways of learning and does not overfit
model = keras.models.Sequential()
model.add(layers.Embedding(num_unique_words, 32))
model.add(layers.Bidirectional(layers.LSTM(64, dropout=0.2, recurrent_dropout=0.2)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(3, activation='softmax'))
model.summary()

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1748108704.206545   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1748108704.301494   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1748108704.301623   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1748108704.309466   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1748108704.309538   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1748108704.309565   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1748108704.432027   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1748108704.432091   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-05-24 13:45:04.432105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2112] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
I0000 00:00:1748108704.432146   69110 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-05-24 13:45:04.432168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1756 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
loss = 'sparse_categorical_crossentropy'
optim = keras.optimizers.Adam(learning_rate=0.001) #from 0.001
metrics = ["accuracy"]

model.compile(loss=loss, optimizer=optim, metrics=metrics)

In [ ]:
print(training_padded.dtype, training_padded.shape)

int32 (1608, 500)

In [ ]:
training_labels = np.array(training_labels).astype(np.int64)
validation_labels = np.array(validation_labels).astype(np.int64)

In [ ]:
print(training_padded.dtype, training_padded.shape)
print(training_labels.dtype, training_labels.shape)

int32 (1608, 500)
int64 (1608,)

In [ ]:
print(training_padded)

[[   47   689   171 ...     0     0     0]
 [  347   224  2807 ...   840   518   621]
 [21035   721   296 ...     0     0     0]
 ...
 [   14   253    87 ...     0     0     0]
 [   47   689   231 ...  1906  1712   376]
 [ 1304   486 19392 ...     0     0     0]]

In [ ]:
print(counter)

Counter({'people': 9977, '—': 8222, 'new': 6587, 'world': 6530, 'work': 6325, 'us': 6261, 'china': 6246, 'countries': 6156, 'development': 6030, 'one': 5367, 'also': 5297, 'country': 5190, 'cooperation': 5139, 'today': 4997, 'need': 4856, 'make': 4751, 'thank': 4400, 'years': 4319, 'like': 4236, 'must': 4210, 'going': 4136, 'want': 4067, 'know': 4061, 'would': 3998, 'it’s': 3995, 'time': 3944, 'international': 3876, 'economic': 3761, 'many': 3709, 'applause': 3698, 'first': 3525, 'we’re': 3520, '–': 3500, 'year': 3467, 'security': 3461, 'united': 3394, 'economy': 3278, 'states': 3250, 'that’s': 3248, 'every': 3222, 'great': 3150, 'important': 3121, 'get': 3113, 'together': 3081, 'american': 3075, 'good': 2925, 'government': 2885, 'way': 2808, 'much': 2796, 'america': 2769, 'support': 2767, 'state': 2744, 'right': 2705, 'global': 2697, 'take': 2653, 'help': 2564, 'well': 2558, 'president': 2520, 'think': 2490, 'two': 2466, 'future': 2365, 'system': 2354, 'national': 2342, 'made': 2333, 'even': 2319, 'russia': 2247, 'law': 2237, 'last': 2180, 'continue': 2167, 'say': 2143, 'we’ve': 2136, 'working': 2110, 'back': 2108, 'growth': 2096, 'chinese': 2063, 'see': 2031, 'peace': 2019, 'americans': 2013, 'trade': 1987, 'said': 1972, 'jobs': 1960, 'better': 1931, 'come': 1918, 'part': 1885, 'still': 1869, 'day': 1800, 'families': 1777, 'including': 1768, 'community': 1750, 'got': 1749, 'business': 1730, 'nation': 1716, 'efforts': 1705, 'build': 1701, 'sure': 1693, 'already': 1687, 'i’m': 1677, 'russian': 1674, 'keep': 1650, 'around': 1650, 'course': 1639, 'progress': 1631, 'let': 1629, 'lives': 1628, 'common': 1627, 'done': 1609, 'health': 1595, 'could': 1594, 'long': 1581, 'life': 1581, 'never': 1568, 'relations': 1521, 'across': 1519, 'political': 1517, 'put': 1516, 'interests': 1513, 'go': 1507, 'place': 1503, 'million': 1487, 'history': 1486, 'war': 1486, 'military': 1485, 'past': 1484, 'may': 1482, 'public': 1473, 'always': 1466, 'regional': 1466, 'nations': 1463, 'social': 1457, 'making': 1447, 'believe': 1432, 'number': 1422, 'change': 1413, 'friends': 1409, 'give': 1402, 'don’t': 1390, 'issues': 1373, 'problems': 1373, 'region': 1364, 'things': 1364, 'investment': 1363, 'job': 1351, 'open': 1346, 'ago': 1339, 'federal': 1334, 'care': 1331, 'hope': 1327, 'lot': 1325, 'forward': 1303, 'situation': 1303, 'set': 1301, 'energy': 1299, 'look': 1298, 'able': 1284, 'end': 1281, 'leaders': 1278, 'home': 1277, 'use': 1274, 'since': 1271, 'next': 1270, 'percent': 1266, 'education': 1255, 'children': 1255, 'citizens': 1251, 'plan': 1244, 'chinas': 1237, 'best': 1236, 'rights': 1232, 'means': 1227, 'they’re': 1226, 'everybody': 1204, 'developing': 1204, 'power': 1196, 'building': 1195, 'ensure': 1192, 'women': 1179, 'major': 1178, 'create': 1176, 'policy': 1169, 'another': 1168, 'ever': 1168, 'clear': 1167, 'foreign': 1165, 'without': 1163, 'possible': 1162, 'congress': 1158, 'strong': 1156, 'meeting': 1153, 'reform': 1144, 'second': 1134, 'society': 1133, 'members': 1129, 'order': 1129, 'businesses': 1128, 'something': 1125, 'hard': 1123, 'areas': 1115, 'different': 1115, 'act': 1112, 'opportunity': 1110, 'free': 1110, 'financial': 1103, 'issue': 1102, 'young': 1100, 'human': 1098, 'africa': 1094, 'three': 1083, 'laughter': 1082, 'times': 1081, 'service': 1079, 'forces': 1074, 'companies': 1065, 'market': 1059, 'big': 1054, 'local': 1049, 'protect': 1046, 'billion': 1045, 'far': 1041, 'workers': 1028, 'family': 1027, 'challenges': 1025, 'regions': 1025, 'others': 1015, 'whole': 1013, 'measures': 1008, 'infrastructure': 1002, 'nuclear': 995, 'colleagues': 993, 'road': 993, 'level': 992, 'respect': 988, 'un': 988, 'general': 986, 'pay': 986, 'provide': 985, 'mutual': 983, 'shared': 979, 'i’ve': 976, 'become': 967, 'council': 958, 'role': 955, 'everyone': 955, 'cannot': 947, 'thing': 945, 'really': 945, 'fight': 937, 'fact': 936, 'special': 932, 'you’re': 932, 'stand': 920, 'needs': 919, 'bring': 918, 'everything': 911, 'resources': 907, 'process': 906, 'god': 904, 'promote': 901, 'increase': 898, 'taking': 896, 'greater': 895, 'stability': 893, 'crisis': 892, 'taken': 887, 'action': 885, 'real': 884, 'share': 884, 'high': 880, 'effective': 876, 'necessary': 875, 'communities': 875, 'deal': 873, 'seen': 872, 'tax': 864, 'peoples': 862, 'climate': 855, 'services': 847, 'force': 847, 'among': 840, 'full': 839, 'opportunities': 839, 'days': 836, 'live': 833, 'partners': 832, 'ready': 822, 'improve': 817, 'there’s': 812, 'start': 811, 'achieve': 809, 'justice': 808, 'prosperity': 804, 'point': 803, 'europe': 800, 'sector': 797, 'parties': 787, 'asia': 785, 'house': 780, 'money': 780, 'months': 778, 'folks': 778, 'meet': 776, 'millions': 775, 'potential': 774, 'strengthen': 764, 'summit': 760, 'step': 758, 'responsibility': 756, 'projects': 755, 'mr': 754, 'five': 754, 'partnership': 753, 'coming': 750, 'attention': 750, 'freedom': 749, 'face': 748, 'technology': 748, 'african': 740, 'address': 738, 'example': 737, 'strategic': 736, 'within': 732, 'problem': 732, 'dear': 731, 'ahead': 730, 'middle': 728, 'thanks': 728, 'innovation': 725, 'getting': 724, 'success': 722, 'yet': 720, 'principles': 718, 'men': 715, 'conditions': 712, 'took': 705, 'especially': 704, 'remember': 703, 'east': 702, 'committed': 701, 'school': 701, 'approach': 700, 'proud': 699, 'entire': 699, 'week': 698, 'key': 697, 'joint': 695, 'love': 693, 'area': 692, 'understand': 691, 'single': 689, 'secretary': 684, 'fully': 684, 'democracy': 682, 'third': 681, 'find': 679, 'afghanistan': 675, 'modern': 674, 'true': 674, 'information': 671, 'office': 670, 'growing': 667, 'terrorism': 665, 'agreement': 664, 'commitment': 662, 'develop': 662, 'less': 657, 'matter': 653, 'minister': 652, 'schools': 651, 'small': 649, 'decades': 648, 'we’ll': 647, 'steps': 645, 'tell': 643, 'rules': 643, 'values': 642, 'given': 641, 'civil': 641, 'moment': 640, 'enforcement': 638, 'often': 636, 'budget': 636, 'task': 635, 'initiative': 635, 'european': 634, 'chance': 633, 'came': 630, 'difficult': 629, 'actions': 628, 'kind': 628, 'union': 628, 'safe': 626, 'administration': 626, 'control': 622, 'quality': 622, 'friendship': 621, 'century': 618, 'results': 617, 'honor': 616, 'incredible': 616, 'fair': 614, 'peaceful': 613, 'decisions': 613, 'can’t': 613, 'benefits': 613, 'south': 612, 'close': 611, 'spirit': 608, 'environment': 608, 'lead': 606, 'leadership': 605, 'dialogue': 603, 'enough': 601, 'path': 601, 'effort': 600, 'rate': 600, 'wish': 597, 'whether': 596, 'used': 596, 'poverty': 594, 'mean': 592, 'finally': 592, 'four': 591, 'move': 587, 'turn': 587, 'stronger': 587, 'sustainable': 586, 'worked': 586, 'focus': 583, 'based': 583, 'laws': 582, 'access': 581, 'police': 581, 'virus': 580, 'changes': 580, 'veterans': 580, 'covid19': 580, 'agenda': 579, 'ways': 578, 'main': 577, 'call': 577, 'thousands': 576, 'little': 576, 'experience': 575, 'threat': 575, 'along': 575, 'bless': 570, 'welcome': 568, 'words': 568, 'makes': 567, 'priority': 566, 'goal': 564, 'capacity': 559, 'remain': 559, 'nearly': 559, 'half': 557, 'created': 555, 'violence': 554, 'ask': 554, 'benefit': 551, 'play': 550, 'serious': 549, 'lost': 549, 'sense': 545, 'stop': 545, 'higher': 545, 'advance': 544, 'helping': 543, 'stay': 541, 'exchanges': 540, 'prime': 540, 'uk': 540, 'living': 539, 'particular': 538, 'science': 536, 'simply': 536, 'talk': 536, 'current': 535, 'trust': 534, 'legal': 534, 'threats': 532, 'ones': 531, 'basis': 530, 'line': 527, 'various': 525, 'recent': 524, 'authorities': 524, 'weeks': 523, 'uphold': 523, 'serve': 521, 'strength': 520, 'nothing': 520, 'allow': 518, 'terrorist': 518, 'governance': 518, 'longterm': 517, 'students': 517, 'you’ve': 517, 'early': 516, 'fighting': 515, 'join': 515, 'comprehensive': 513, 'reason': 512, 'party': 512, 'almost': 511, 'groups': 511, 'agencies': 510, 'behind': 509, 'responsible': 508, 'helped': 507, 'strategy': 506, 'grow': 506, 'winwin': 506, 'gentlemen': 503, 'away': 502, 'plans': 502, 'old': 502, 'xi': 502, 'discuss': 501, 'assistance': 499, 'generation': 498, 'training': 496, 'britain': 496, 'bill': 495, 'let’s': 495, 'pursue': 494, 'remains': 493, 'ladies': 493, 'industrial': 493, 'actually': 493, 'border': 493, 'standards': 492, 'ministry': 492, 'safety': 491, 'industry': 490, 'creating': 490, 'thats': 490, 'institutions': 487, 'relationship': 487, 'called': 485, 'month': 484, 'top': 484, 'large': 483, 'basic': 482, 'positive': 481, 'vision': 480, 'forum': 480, 'built': 478, 'russia’s': 477, 'visit': 476, 'city': 476, 'hold': 475, 'cases': 475, 'culture': 474, 'asean': 474, 'speak': 473, 'america’s': 473, 'central': 473, 'armed': 472, 'country’s': 471, 'cut': 471, 'prevent': 471, 'private': 470, 'research': 469, 'enhance': 467, 'victory': 467, 'belt': 467, 'looking': 466, 'several': 466, 'following': 464, 'eu': 464, 'north': 463, 'developed': 462, 'production': 462, 'met': 462, 'resolve': 461, 'challenge': 460, 'space': 459, 'significant': 457, 'case': 457, 'protection': 456, 'active': 456, 'largest': 455, 'beyond': 454, 'follow': 454, 'held': 453, 'ideas': 453, 'class': 452, 'goals': 451, 'response': 451, 'faith': 451, 'terrorists': 450, 'signed': 450, 'anniversary': 449, 'pandemic': 449, 'ground': 447, 'happen': 447, 'housing': 447, 'position': 445, 'truly': 445, 'expand': 445, 'involved': 445, 'passed': 444, 'save': 443, 'markets': 443, 'soon': 443, 'economies': 442, 'asian': 442, 'raise': 442, 'deliver': 442, 'feel': 442, 'leading': 440, 'least': 440, 'sides': 439, 'result': 438, 'land': 435, 'recovery': 434, 'weapons': 433, 'leave': 433, 'interest': 433, 'saying': 433, 'seek': 430, 'legislation': 430, 'certain': 430, 'medical': 429, 'foundation': 428, 'fundamental': 428, 'events': 427, 'decision': 427, 'coordination': 426, 'reduce': 426, 'troops': 425, 'vital': 424, 'equal': 424, 'question': 424, 'member': 423, 'begin': 422, 'brought': 422, 'left': 421, 'however': 420, 'group': 418, 'present': 417, 'mission': 416, 'cities': 416, 'choice': 416, 'tasks': 416, 'historic': 416, 'isil': 416, 'syria': 415, 'child': 415, 'what’s': 415, 'jointly': 414, 'affairs': 414, 'comes': 412, 'rest': 412, 'idea': 411, 'might': 411, 'six': 411, 'trying': 411, 'courage': 410, 'domestic': 410, 'hear': 409, 'policies': 408, 'dollars': 408, 'systems': 408, 'officers': 407, 'confidence': 406, 'representatives': 405, 'needed': 405, 'insurance': 405, 'relevant': 404, 'carry': 404, 'iraq': 404, 'contribution': 404, 'overall': 403, 'extraordinary': 403, 'reach': 403, 'secure': 403, 'afternoon': 402, 'critical': 402, '10': 402, 'agree': 402, 'cost': 402, 'personnel': 401, 'period': 401, 'actively': 400, 'show': 400, 'talking': 400, 'man': 399, 'they’ve': 399, 'please': 397, 'happened': 397, 'importance': 396, 'cultural': 395, 'therefore': 395, 'democratic': 394, 'terms': 394, 'rather': 394, 'dignity': 393, 'technologies': 393, 'heard': 393, 'heart': 391, 'federation': 391, 'goods': 389, 'manufacturing': 389, 'towards': 388, 'diplomacy': 387, 'iran': 386, 'sometimes': 385, 'organizations': 385, 'vote': 384, 'drug': 384, 'kids': 384, 'equipment': 384, 'instead': 383, 'demand': 381, 'risk': 381, 'yesterday': 381, 'doesn’t': 379, 'levels': 379, 'criminal': 379, 'affordable': 379, 'diplomatic': 379, 'green': 378, 'alone': 377, 'framework': 376, 'huge': 376, 'executive': 375, 'particularly': 375, 'longer': 375, 'heads': 375, 'supply': 374, 'fellow': 374, 'implement': 373, 'speaker': 373, 'republicans': 373, 'biggest': 373, 'recently': 373, '100': 373, 'view': 372, 'crime': 372, 'allies': 371, '50': 371, 'ensuring': 371, 'side': 370, 'stage': 370, 'increasing': 370, 'stable': 369, 'beautiful': 369, 'white': 369, '20': 368, 'weve': 367, 'team': 367, 'agreed': 365, 'invest': 365, 'goes': 365, 'saw': 364, 'investments': 364, 'british': 364, 'promoting': 363, 'rule': 363, 'absolutely': 363, 'understanding': 362, 'people’s': 362, 'beginning': 362, 'paid': 362, 'greatest': 362, 'story': 362, 'achieved': 361, 'throughout': 361, 'places': 360, 'hand': 359, 'activities': 359, 'improving': 359, 'republic': 358, 'encourage': 358, 'didn’t': 358, 'jinping': 358, 'spread': 357, 'additional': 356, 'toward': 356, 'told': 356, 'went': 355, 'stress': 354, 'works': 354, 'conflict': 353, 'capital': 353, 'governments': 353, 'defence': 353, 'started': 352, 'try': 351, 'maintain': 351, 'department': 351, 'integration': 351, 'implementation': 350, 'fourth': 349, 'exchange': 349, 'effectively': 349, 'costs': 349, 'internet': 349, 'sea': 348, 'draw': 348, 'directly': 348, 'though': 348, 'morning': 347, 'impact': 346, 'asiapacific': 346, 'independent': 346, 'thought': 346, 'successful': 345, 'opening': 345, 'humanitarian': 344, 'pass': 344, 'faster': 344, 'majority': 344, 'facing': 344, 'person': 343, 'nhs': 343, 'direct': 343, 'fund': 341, 'gave': 341, 'moving': 340, 'increased': 340, 'politics': 340, 'regime': 339, 'differences': 338, 'immigration': 338, 'practical': 338, 'duty': 337, 'contribute': 337, 'mind': 336, 'reached': 336, 'natural': 336, 'ultimately': 336, 'despite': 336, 'conference': 335, 'tough': 335, 'election': 335, 'proposals': 334, 'mechanisms': 333, 'clean': 333, 'happy': 333, 'partner': 333, 'air': 333, 'disease': 332, 'population': 332, 'ability': 331, 'starting': 331, 'account': 330, 'i’ll': 330, 'inclusive': 329, 'west': 328, 'vaccine': 328, 'generations': 328, 'confident': 328, 'funding': 328, 'competition': 328, 'loved': 328, 'offer': 327, 'today’s': 327, 'wages': 327, 'college': 327, 'hands': 327, 'deepen': 326, 'products': 326, 'quickly': 325, 'army': 324, 'upon': 324, 'water': 324, 'truth': 324, 'protecting': 324, 'indeed': 324, 'wanted': 324, 'media': 323, 'principle': 323, 'else': 323, 'defend': 323, 'anything': 322, 'discussion': 322, 'using': 322, 'announced': 322, 'unity': 321, '1': 321, 'behalf': 321, 'transport': 321, 'program': 321, 'lower': 320, 'he’s': 320, 'joined': 320, 'sco': 320, 'defense': 319, 'outstanding': 319, 'programme': 319, 'data': 318, 'model': 318, 'cause': 318, 'parents': 317, 'closely': 317, 'ties': 317, 'world’s': 317, 'concerns': 317, 'whose': 316, 'bilateral': 316, 'discussed': 316, 'unemployment': 315, 'expect': 314, 'willing': 314, 'gives': 313, 'quite': 313, 'fought': 313, 'later': 312, 'dangerous': 311, 'providing': 311, 'hundreds': 311, 'per': 310, 'strengthening': 310, 'form': 309, 'food': 308, 'seeing': 308, 'rise': 308, 'debt': 307, 'washington': 307, 'giving': 306, 'known': 306, 'mankind': 306, 'firmly': 306, 'boost': 305, 'promise': 305, 'priorities': 305, 'religious': 304, 'operations': 304, 'risks': 304, 'industries': 304, 'happening': 304, 'scientific': 303, 'vaccines': 302, 'g20': 302, 'direction': 300, 'neighbors': 300, 'spending': 300, 'construction': 299, 'agreements': 299, 'value': 299, 'environmental': 299, 'unfortunately': 298, 'message': 298, 'multilateral': 298, 'includes': 298, 'practice': 298, 'room': 297, 'gone': 297, 'friend': 297, 'officials': 297, 'forget': 297, 'total': 297, 'supporting': 295, 'simple': 295, 'nature': 295, 'advanced': 294, 'easy': 294, 'anyone': 293, 'organisations': 293, 'closer': 293, 'tremendous': 293, 'attack': 292, 'india': 292, 'average': 291, 'return': 290, 'emergency': 290, 'asked': 289, 'parts': 289, 'staff': 289, 'yes': 288, 'sectors': 288, 'reforms': 288, 'project': 287, '15': 286, 'putting': 285, 'requires': 285, 'abroad': 285, 'gas': 285, 'powerful': 285, 'keeping': 284, 'appreciate': 284, 'fast': 284, 'borders': 284, 'effect': 283, 'news': 283, 'earlier': 283, 'provided': 282, 'achievements': 282, 'seven': 282, 'learn': 281, 'establish': 281, 'age': 281, 'established': 281, 'wrong': 281, 'specific': 280, 'universities': 280, 'range': 280, 'initiatives': 280, 'dream': 280, 'attacks': 280, 'field': 279, 'hearts': 279, 'corruption': 279, 'responsibilities': 278, 'difficulties': 278, 'trend': 278, 'silk': 278, 'grateful': 278, 'decade': 277, 'campaign': 277, 'individual': 276, 'financing': 276, 'paying': 276, 'equality': 276, 'governor': 275, 'heroes': 275, 'found': 275, 'moscow': 275, 'available': 275, 'constitution': 275, 'independence': 274, 'senate': 273, 'record': 273, 'aid': 273, 'oil': 273, 'spent': 273, 'prepared': 272, 'taxes': 272, 'traditional': 272, '21st': 271, 'night': 271, 'treaty': 270, 'personal': 270, 'bringing': 270, 'speed': 270, 'changing': 270, 'won’t': 270, 'report': 269, 'healthcare': 269, 'clearly': 269, 'learning': 269, '40': 268, 'competitive': 268, 'sphere': 268, 'openingup': 268, 'determined': 267, 'note': 267, 'continues': 267, 'chinaafrica': 267, 'difference': 266, 'sound': 266, 'test': 266, 'unique': 266, 'essential': 264, 'front': 264, 'operation': 264, 'spoke': 264, '30': 264, 'court': 264, 'consider': 263, 'continued': 263, 'conclusion': 263, 'crimes': 263, 'due': 262, 'aware': 262, 'outside': 261, 'consultation': 261, 'homes': 261, 'consensus': 261, 'importantly': 261, 'sacrifice': 261, 'led': 260, 'pursuing': 260, 'innovative': 260, 'humanity': 259, 'complete': 259, 'sovereignty': 259, 'bank': 259, 'thinking': 259, 'questions': 258, 'steady': 257, 'takes': 257, 'complex': 257, 'standing': 257, 'obviously': 257, 'drugs': 257, 'win': 257, 'negotiations': 256, 'run': 256, 'certainly': 256, 'historical': 256, 'connectivity': 256, 'civilizations': 256, 'programmes': 256, 'easier': 255, 'enormous': 255, 'scale': 255, 'trillion': 254, 'cuts': 254, 'powers': 253, 'teachers': 253, 'pressure': 253, 'facilities': 253, 'nato': 253, 'organization': 253, 'center': 252, 'adopted': 252, 'balanced': 252, 'earth': 252, 'vaccinated': 252, 'solution': 251, 'supported': 251, 'whatever': 251, 'final': 251, 'nobody': 251, 'combat': 250, 'multilateralism': 250, 'prosperous': 249, 'crucial': 249, 'vast': 249, 'sign': 249, 'focused': 249, 'core': 249, 'leader': 248, 'subject': 248, 'john': 248, 'authority': 247, 'foster': 247, 'founding': 247, 'receive': 247, 'apec': 247, 'meetings': 246, 'tomorrow': 246, 'solidarity': 246, 'shows': 246, 'solve': 245, 'purpose': 245, 'presidential': 245, 'killed': 245, 'distinguished': 244, 'profound': 244, 'thus': 244, 'technological': 243, 'deserve': 243, 'celebrate': 243, 'drive': 243, 'forms': 241, 'mechanism': 240, 'prices': 240, 'express': 240, 'skills': 240, 'served': 240, 'settlement': 239, 'experts': 239, 'event': 239, 'deeply': 239, 'company': 239, 'respond': 238, 'reality': 238, 'assembly': 238, 'management': 238, 'short': 238, 'proposed': 237, 'treatment': 237, 'send': 237, 'duma': 237, 'coalition': 236, 'concerned': 236, 'repeat': 236, 'matters': 236, 'stands': 236, 'ukraine': 236, 'participation': 235, 'extremism': 235, 'bipartisan': 235, 'democrats': 235, 'emerging': 235, 'rescue': 235, 'charter': 235, 'momentum': 235, 'require': 234, 'internal': 234, 'recognize': 234, 'bigger': 234, 'collective': 234, 'organisation': 234, 'era': 234, 'existing': 233, 'received': 233, 'individuals': 233, '70': 232, 'peninsula': 232, 'openness': 231, 'amount': 231, 'battle': 231, 'brics': 230, 'reasons': 229, 'fire': 229, 'began': 229, 'doubt': 229, 'buy': 229, 'shot': 229, 'korean': 229, 'trading': 228, 'according': 228, 'head': 228, 'ten': 228, 'highest': 228, 'succeed': 228, 'changed': 228, 'digital': 228, 'mass': 228, 'professional': 228, 'bodies': 228, 'funds': 228, 'nation’s': 228, 'structure': 227, 'rates': 227, 'solid': 227, 'serving': 227, 'concrete': 226, 'bad': 226, 'gun': 226, 'wonderful': 225, 'light': 225, 'gdp': 225, 'fear': 225, 'conflicts': 225, 'creation': 224, 'sent': 224, 'credit': 224, 'influence': 224, 'properly': 224, 'addition': 223, 'choose': 223, 'programs': 223, 'commitments': 223, 'rural': 223, 'income': 223, 'roads': 223, 'review': 222, 'deep': 222, 'launched': 222, 'carried': 222, 'bit': 221, 'price': 221, '2020': 220, 'deficit': 220, 'highly': 220, 'break': 220, 'statement': 219, 'faced': 219, 'guests': 219, 'rising': 219, 'discussions': 219, 'vice': 219, 'covid': 218, 'extremely': 218, 'spend': 218, 'although': 217, 'soldiers': 217, 'host': 216, 'hit': 216, 'realize': 215, 'arms': 215, 'overcome': 214, 'planet': 214, 'comm

In [ ]:
##making sure that overrepresentation of a class does not affect the model
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(training_labels),
    y=training_labels
)
class_weights = dict(enumerate(class_weights))

In [ ]:
class_weights

{0: 1.1189979123173277, 1: 0.6090909090909091, 2: 2.1526104417670684}

In [ ]:
model.fit(training_padded, training_labels, epochs=10, validation_data=(validation_padded, validation_labels), class_weight=class_weights, batch_size=32, verbose=2)

Epoch 1/10
51/51 - 175s - 3s/step - accuracy: 0.3221 - loss: 1.0958 - val_accuracy: 0.2861 - val_loss: 1.0946
Epoch 2/10
51/51 - 170s - 3s/step - accuracy: 0.3284 - loss: 1.0472 - val_accuracy: 0.3134 - val_loss: 1.0811
Epoch 3/10
51/51 - 164s - 3s/step - accuracy: 0.5292 - loss: 0.7795 - val_accuracy: 0.4030 - val_loss: 1.1723
Epoch 4/10
51/51 - 159s - 3s/step - accuracy: 0.7767 - loss: 0.4496 - val_accuracy: 0.4876 - val_loss: 1.3118
Epoch 5/10
51/51 - 160s - 3s/step - accuracy: 0.8825 - loss: 0.2825 - val_accuracy: 0.4776 - val_loss: 1.7079
Epoch 6/10
51/51 - 169s - 3s/step - accuracy: 0.9484 - loss: 0.1431 - val_accuracy: 0.5373 - val_loss: 2.1272
Epoch 7/10
51/51 - 171s - 3s/step - accuracy: 0.9689 - loss: 0.0994 - val_accuracy: 0.5423 - val_loss: 2.0804
Epoch 8/10
51/51 - 170s - 3s/step - accuracy: 0.9720 - loss: 0.0961 - val_accuracy: 0.5398 - val_loss: 2.1094
Epoch 9/10
51/51 - 170s - 3s/step - accuracy: 0.9789 - loss: 0.0523 - val_accuracy: 0.5050 - val_loss: 2.6492
Epoch 10/10
51/51 - 164s - 3s/step - accuracy: 0.9726 - loss: 0.0748 - val_accuracy: 0.5373 - val_loss: 2.1828

# Adding in L2 Regularization and Dropout to the Model to Prevent Overfitting

In [ ]:
#LSTM Model

from tensorflow.keras import regularizers


#embedding layer converts the words into vectors of fixed size
#dropout rate drops out a certain percentage of input data so that the
#model learns more robust ways of learning and does not overfit
#l2 regularization is used to prevent large weights from being learned, and thus less overfitting

model = keras.models.Sequential()
model.add(layers.Embedding(num_unique_words, 32))
model.add(layers.Bidirectional(layers.LSTM(64, dropout=0.4, recurrent_dropout=0.4)))
model.add(layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(layers.Dense(3, activation='softmax'))
model.summary()



loss = 'sparse_categorical_crossentropy'
optim = keras.optimizers.Adam(learning_rate=0.001) #from 0.001
metrics = ["accuracy"]

model.compile(loss=loss, optimizer=optim, metrics=metrics)


model.fit(training_padded, training_labels, epochs=20, validation_data=(validation_padded, validation_labels), class_weight=class_weights, batch_size=32, verbose=2)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_3 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
51/51 - 175s - 3s/step - accuracy: 0.3986 - loss: 1.2501 - val_accuracy: 0.4403 - val_loss: 1.1936
Epoch 2/20
51/51 - 167s - 3s/step - accuracy: 0.4627 - loss: 1.1634 - val_accuracy: 0.5771 - val_loss: 1.1028
Epoch 3/20
51/51 - 161s - 3s/step - accuracy: 0.5721 - loss: 1.0514 - val_accuracy: 0.5373 - val_loss: 1.0537
Epoch 4/20
51/51 - 170s - 3s/step - accuracy: 0.6629 - loss: 0.8566 - val_accuracy: 0.5697 - val_loss: 1.0006
Epoch 5/20

KeyboardInterrupt:

# Implementation of Bayesian Optimization For Hyperparameter Tuning